MUSI6106: CCombFilterIf Class Reference
CCombFilterIf Class Reference
interface class for the comb filter (FIR & IIR)
#include <CombFilterIf.h>
Public Types
enum Version_t { kMajor , kMinor , kPatch , kNumVersionInts }
enum CombFilterType_t { kCombFIR , kCombIIR , kNumFilterTypes }
enum FilterParam_t { kParamGain , kParamDelay , kNumFilterParams }
Public Member Functions
Error_t init (CombFilterType_t eFilterType, float fMaxDelayLengthInS, float fSampleRateInHz, int iNumChannels)
Error_t reset ()
Error_t setParam (FilterParam_t eParam, float fParamValue)
float getParam (FilterParam_t eParam) const
Error_t process (float **ppfInputBuffer, float **ppfOutputBuffer, int iNumberOfFrames)
Static Public Member Functions
static const int getVersion (const Version_t eVersionIdx)
static const char * getBuildDate ()
static Error_t create (CCombFilterIf *&pCCombFilterIf)
static Error_t destroy (CCombFilterIf *&pCCombFilterIf)
Protected Member Functions
CCombFilterIf ()
virtual ~CCombFilterIf ()
Private Attributes
bool m_bIsInitialized
internal bool to check whether the init function has been called
CCombFilterBase * m_pCCombFilter
handle of the comb filter
float m_fSampleRate
audio sample rate in Hz
Detailed Description
interface class for the comb filter (FIR & IIR)
Definition at line 10 of file CombFilterIf.h.
Member Enumeration Documentation
CombFilterType_t
enum CCombFilterIf::CombFilterType_t
feedforward or recursive comb filter
Enumerator
kCombFIR
finite impulse response filter
kCombIIR
infinite impulse response filter
kNumFilterTypes
Definition at line 24 of file CombFilterIf.h.
    {
        kCombFIR,           //!< finite impulse response filter
        kCombIIR,           //!< infinite impulse response filter
        kNumFilterTypes
    };
FilterParam_t
enum CCombFilterIf::FilterParam_t
list of parameters for the comb filters
Enumerator
kParamGain
gain as factor (usually -1...1)
kParamDelay
delay in seconds for specification of comb width
kNumFilterParams
Definition at line 33 of file CombFilterIf.h.
    {
        kParamGain,         //!< gain as factor (usually -1...1)
        kParamDelay,        //!< delay in seconds for specification of comb width
        kNumFilterParams
    };
Version_t
enum CCombFilterIf::Version_t
version number
Enumerator
kMajor
major version number
kMinor
minor version number
kPatch
patch version number
kNumVersionInts
Definition at line 14 of file CombFilterIf.h.
    {
        kMajor,             //!< major version number
        kMinor,             //!< minor version number
        kPatch,             //!< patch version number
        kNumVersionInts
    };
Constructor & Destructor Documentation
CCombFilterIf()
CCombFilterIf::CCombFilterIf () protected
Definition at line 17 of file CombFilterIf.cpp.
                              :
    m_bIsInitialized(false),
    m_pCCombFilter(0),
    m_fSampleRate(0)
{
    // this never hurts
    this->reset ();
}
References reset().
Referenced by create().
~CCombFilterIf()
CCombFilterIf::~CCombFilterIf () protected virtual
Definition at line 27 of file CombFilterIf.cpp.
{
    this->reset ();
}
References reset().
Member Function Documentation
create()
Error_t CCombFilterIf::create (CCombFilterIf *& pCCombFilterIf) static
creates a new comb filter instance
Parameters
pCCombFilterIf pointer to the new class
Returns
Error_t
Definition at line 59 of file CombFilterIf.cpp.
{
    pCMyProject = new CCombFilterIf ();
    if (!pCMyProject)
        return Error_t::kUnknownError;
    return Error_t::kNoError;
}
References CCombFilterIf(), kNoError, and kUnknownError.
destroy()
Error_t CCombFilterIf::destroy (CCombFilterIf *& pCCombFilterIf) static
destroys a comb filter instance
Parameters
pCCombFilterIf pointer to the class to be destroyed
Returns
Error_t
Definition at line 70 of file CombFilterIf.cpp.
{
    if (!pCMyProject)
        return Error_t::kUnknownError;
    pCMyProject->reset ();
    delete pCMyProject;
    pCMyProject = 0;
    return Error_t::kNoError;
}
References kNoError, kUnknownError, and reset().
getBuildDate()
const char * CCombFilterIf::getBuildDate () static
returns the date of the build
Returns
const char*
Definition at line 54 of file CombFilterIf.cpp.
{
    return kCMyProjectBuildDate;
}
References kCMyProjectBuildDate.
getParam()
float CCombFilterIf::getParam (FilterParam_t eParam) const
return the value of the specified parameter
Parameters
eParam
Returns
float
Definition at line 143 of file CombFilterIf.cpp.
{
    if (!m_bIsInitialized)
        return -1;
    switch (eParam)
    {
    case kParamDelay:
        return m_pCCombFilter->getParam(eParam) / m_fSampleRate;
    default:
    case kParamGain:
        return m_pCCombFilter->getParam (eParam);
    }
}
References CCombFilterBase::getParam(), kParamDelay, kParamGain, m_bIsInitialized, m_fSampleRate, and m_pCCombFilter.
getVersion()
const int CCombFilterIf::getVersion (const Version_t eVersionIdx) static
returns the current project version
Parameters
eVersionIdx specifies what version to return (kMajor, kMinor,...)
Returns
const int
Definition at line 32 of file CombFilterIf.cpp.
{
    int iVersion = 0;
    switch (eVersionIdx)
    {
    case kMajor:
        iVersion    = MUSI6106_VERSION_MAJOR;
        break;
    case kMinor:
        iVersion    = MUSI6106_VERSION_MINOR;
        break;
    case kPatch:
        iVersion    = MUSI6106_VERSION_PATCH;
        break;
    case kNumVersionInts:
        iVersion    = -1;
        break;
    }
    return iVersion;
}
References kMajor, kMinor, kNumVersionInts, kPatch, MUSI6106_VERSION_MAJOR, MUSI6106_VERSION_MINOR, and MUSI6106_VERSION_PATCH.
init()
Error_t CCombFilterIf::init (CombFilterType_t eFilterType, float fMaxDelayLengthInS, float fSampleRateInHz, int iNumChannels)
initializes a comb filter instance
Parameters
eFilterType FIR or IIR
fMaxDelayLengthInS maximum allowed delay in seconds
fSampleRateInHz sample rate in Hz
iNumChannels number of audio channels
Returns
Error_t
Definition at line 84 of file CombFilterIf.cpp.
{
    reset();
    if (fMaxDelayLengthInS <= 0 ||
        fSampleRateInHz <= 0 ||
        iNumChannels <= 0)
        return Error_t::kFunctionInvalidArgsError;
    switch (eFilterType)
    {
    case kCombFIR:
        m_pCCombFilter  = static_cast<CCombFilterBase*> (new CCombFilterFir (CUtil::float2int<int>(fMaxDelayLengthInS * fSampleRateInHz), iNumChannels));
        break;
    case kCombIIR:
        m_pCCombFilter  = static_cast<CCombFilterBase*> (new CCombFilterIir (CUtil::float2int<int>(fMaxDelayLengthInS * fSampleRateInHz), iNumChannels));
        break;
    }
    m_fSampleRate       = fSampleRateInHz;
    m_bIsInitialized    = true;
    return Error_t::kNoError;
}
References kCombFIR, kCombIIR, kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_fSampleRate, m_pCCombFilter, and reset().
process()
Error_t CCombFilterIf::process (float ** ppfInputBuffer, float ** ppfOutputBuffer, int iNumberOfFrames)
processes one block of audio
Parameters
ppfInputBuffer input buffer [numChannels][iNumberOfFrames]
ppfOutputBuffer output buffer [numChannels][iNumberOfFrames]
iNumberOfFrames buffer length (per channel)
Returns
Error_t
Definition at line 120 of file CombFilterIf.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    return m_pCCombFilter->process(ppfInputBuffer, ppfOutputBuffer, iNumberOfFrames);
}
References kNotInitializedError, m_bIsInitialized, m_pCCombFilter, and CCombFilterBase::process().
reset()
Error_t CCombFilterIf::reset ()
resets the internal variables (requires new call of init)
Returns
Error_t
Definition at line 109 of file CombFilterIf.cpp.
{
    delete m_pCCombFilter;
    m_pCCombFilter      = 0;
    m_fSampleRate       = 0;
    m_bIsInitialized    = false;
    return Error_t::kNoError;
}
References kNoError, m_bIsInitialized, m_fSampleRate, and m_pCCombFilter.
Referenced by CCombFilterIf(), destroy(), init(), and ~CCombFilterIf().
setParam()
Error_t CCombFilterIf::setParam (FilterParam_t eParam, float fParamValue)
sets a comb filter parameter
Parameters
eParam what parameter (see ::FilterParam_t)
fParamValue value of the parameter
Returns
Error_t
Definition at line 128 of file CombFilterIf.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    switch (eParam)
    {
    case kParamDelay:
        return m_pCCombFilter->setParam(eParam, fParamValue * m_fSampleRate);
    default:
    case kParamGain:
        return m_pCCombFilter->setParam(eParam, fParamValue);
    }
}
References kNotInitializedError, kParamDelay, kParamGain, m_bIsInitialized, m_fSampleRate, m_pCCombFilter, and CCombFilterBase::setParam().
Member Data Documentation
m_bIsInitialized
bool CCombFilterIf::m_bIsInitialized private
internal bool to check whether the init function has been called
Definition at line 104 of file CombFilterIf.h.
Referenced by getParam(), init(), process(), reset(), and setParam().
m_fSampleRate
float CCombFilterIf::m_fSampleRate private
audio sample rate in Hz
Definition at line 107 of file CombFilterIf.h.
Referenced by getParam(), init(), reset(), and setParam().
m_pCCombFilter
CCombFilterBase* CCombFilterIf::m_pCCombFilter private
handle of the comb filter
Definition at line 105 of file CombFilterIf.h.
Referenced by getParam(), init(), process(), reset(), and setParam().
The documentation for this class was generated from the following files:
CombFilterIf.h
CombFilterIf.cpp