MUSI6106: CVector Class Reference
CVector Class Reference
class with static functions for buffer operations with type T
#include <Vector.h>
Static Public Member Functions
template<typename T >
static void setZero (T *pfSrcDest, long long int iLength)
template<typename T >
static void setZeroBelowThresh (T *pfSrcDest, long long int iLength, T Thresh)
template<typename T >
static void copy (T *pDest, const T *pSource, long long int iLength)
template<typename T >
static void flip_I (T *pfSrcDest, long long int iLength)
template<typename T >
static void moveInMem (T *pfSrcDest, int iDestIdx, int iSrcIdx, long long int iLength)
Detailed Description
class with static functions for buffer operations with type T
Definition at line 11 of file Vector.h.
Member Function Documentation
copy()
template<typename T > static void CVector::copy (T * pDest, const T * pSource, long long int iLength) inline static
copies buffer of type T
Parameters
pDest pointer to destination memory
pSource pointer to source memory
iLength length of buffer
Returns
void
Definition at line 51 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(pDest);
            assert(pSource);
            memcpy(pDest, pSource, sizeof(T)*iLength);
        }
    }
Referenced by CVectorFloat::copy(), and CAudioFileSndLib::openFile().
flip_I()
template<typename T > static void CVector::flip_I (T * pfSrcDest, long long int iLength) inline static
reverses buffer (last to first element)
Parameters
pfSrcDest pointer to memory to be flipped
iLength number of elements
Returns
void
Definition at line 68 of file Vector.h.
    {
        assert(iLength >= 0);
        if (iLength > 0)
        {
            assert(pfSrcDest);
            auto iLoopLength = iLength / 2; // integer division!
            for (auto i = 0; i < iLoopLength; i++)
            {
                T Tmp = pfSrcDest[i];
                pfSrcDest[i] = pfSrcDest[iLength - 1 - i];
                pfSrcDest[iLength - 1 - i] = Tmp;
            }
        }
    }
Referenced by CVectorFloat::flip_I().
moveInMem()
template<typename T > static void CVector::moveInMem (T * pfSrcDest, int iDestIdx, int iSrcIdx, long long int iLength) inline static
moves a subset of the current buffer
Parameters
pfSrcDest source and destination
iDestIdx destination index
iSrcIdx source index
iLength number of elements to be moved
Returns
void
Definition at line 93 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        if (iLength > 0)
            memmove (&pfSrcDest[iDestIdx], &pfSrcDest[iSrcIdx], sizeof(T)*iLength);
    }
Referenced by CVectorFloat::moveInMem().
setZero()
template<typename T > static void CVector::setZero (T * pfSrcDest, long long int iLength) inline static
sets a buffer to zero
Parameters
pfSrcDest pointer to memory to be modified
iLength buffer length
Returns
void
Definition at line 20 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        if (iLength > 0)
            memset (pfSrcDest, 0, sizeof(T)*iLength);
    }
Referenced by CVectorFloat::setZero().
setZeroBelowThresh()
template<typename T > static void CVector::setZeroBelowThresh (T * pfSrcDest, long long int iLength, T Thresh) inline static
sets all values smaller than a threshold to 0
Parameters
pfSrcDest pointer to memory to be modified
iLength buffer length
Thresh threshold value
Returns
void
Definition at line 35 of file Vector.h.
    {
        assert (iLength >= 0);
        assert (pfSrcDest);
        for (auto i = 0; i < iLength; i++)
            if (pfSrcDest[i] < Thresh)
                pfSrcDest[i] = 0;
    }
Referenced by CVectorFloat::setZeroBelowThresh().
The documentation for this class was generated from the following file:
Vector.h