MUSI6106: gtest-internal-inl.h File Reference
gtest-internal-inl.h File Reference
#include <errno.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include "gtest/internal/gtest-port.h"
#include "gtest/gtest.h"
#include "gtest/gtest-spi.h"
Classes
class testing::internal::GTestFlagSaver
class testing::internal::TestPropertyKeyIs
class testing::internal::UnitTestOptions
class testing::internal::OsStackTraceGetterInterface
class testing::internal::OsStackTraceGetter
struct testing::internal::TraceInfo
class testing::internal::DefaultGlobalTestPartResultReporter
class testing::internal::DefaultPerThreadTestPartResultReporter
class testing::internal::UnitTestImpl
class testing::internal::TestResultAccessor
Namespaces
namespace testing
namespace testing::internal
Functions
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251) GTEST_DECLARE_bool_(death_test_use_fork)
GTEST_API_ TimeInMillis testing::internal::GetTimeInMillis ()
GTEST_API_ bool testing::internal::ShouldUseColor (bool stdout_is_tty)
GTEST_API_ std::string testing::internal::FormatTimeInMillisAsSeconds (TimeInMillis ms)
GTEST_API_ std::string testing::internal::FormatEpochTimeInMillisAsIso8601 (TimeInMillis ms)
GTEST_API_ bool testing::internal::ParseFlag (const char *str, const char *flag, int32_t *value)
int testing::internal::GetRandomSeedFromFlag (int32_t random_seed_flag)
int testing::internal::GetNextRandomSeed (int seed)
GTEST_API_ std::string testing::internal::CodePointToUtf8 (uint32_t code_point)
GTEST_API_ std::string testing::internal::WideStringToUtf8 (const wchar_t *str, int num_chars)
void testing::internal::WriteToShardStatusFileIfNeeded ()
GTEST_API_ bool testing::internal::ShouldShard (const char *total_shards_str, const char *shard_index_str, bool in_subprocess_for_death_test)
GTEST_API_ int32_t testing::internal::Int32FromEnvOrDie (const char *env_var, int32_t default_val)
GTEST_API_ bool testing::internal::ShouldRunTestOnShard (int total_shards, int shard_index, int test_id)
template<class Container , typename Predicate >
int testing::internal::CountIf (const Container &c, Predicate predicate)
template<class Container , typename Functor >
void testing::internal::ForEach (const Container &c, Functor functor)
template<typename E >
E testing::internal::GetElementOr (const std::vector< E > &v, int i, E default_value)
template<typename E >
void testing::internal::ShuffleRange (internal::Random *random, int begin, int end, std::vector< E > *v)
template<typename E >
void testing::internal::Shuffle (internal::Random *random, std::vector< E > *v)
template<typename T >
static void testing::internal::Delete (T *x)
GTEST_API_ FilePath testing::internal::GetCurrentExecutableName ()
class UnitTestImpl * testing::internal::GetUnitTestImpl ()
GTEST_API_ void testing::internal::ParseGoogleTestFlagsOnly (int *argc, char **argv)
GTEST_API_ void testing::internal::ParseGoogleTestFlagsOnly (int *argc, wchar_t **argv)
Variables
GTEST_API_ const TypeId testing::internal::kTestTypeIdInGoogleTest
const int testing::internal::kMaxRandomSeed = 99999
GTEST_API_ bool testing::internal::g_help_flag
class testing::internal::GTestFlagSaver testing::internal::GTEST_ATTRIBUTE_UNUSED_
Function Documentation
GTEST_DISABLE_MSC_WARNINGS_PUSH_()
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251 GMOCK_MAYBE_5046_)
Definition at line 46 of file gmock-cardinalities.h.
                  {
// To implement a cardinality Foo, define:
//   1. a class FooCardinality that implements the
//      CardinalityInterface interface, and
//   2. a factory function that creates a Cardinality object from a
//      const FooCardinality*.
//
// The two-level delegation design follows that of Matcher, providing
// consistency for extension developers.  It also eases ownership
// management as Cardinality objects can now be copied like plain values.
// The implementation of a cardinality.
class CardinalityInterface {
 public:
  virtual ~CardinalityInterface() {}
  // Conservative estimate on the lower/upper bound of the number of
  // calls allowed.
  virtual int ConservativeLowerBound() const { return 0; }
  virtual int ConservativeUpperBound() const { return INT_MAX; }
  // Returns true if and only if call_count calls will satisfy this
  // cardinality.
  virtual bool IsSatisfiedByCallCount(int call_count) const = 0;
  // Returns true if and only if call_count calls will saturate this
  // cardinality.
  virtual bool IsSaturatedByCallCount(int call_count) const = 0;
  // Describes self to an ostream.
  virtual void DescribeTo(::std::ostream* os) const = 0;
};
// A Cardinality is a copyable and IMMUTABLE (except by assignment)
// object that specifies how many times a mock function is expected to
// be called.  The implementation of Cardinality is just a std::shared_ptr
// to const CardinalityInterface. Don't inherit from Cardinality!
class GTEST_API_ Cardinality {
 public:
  // Constructs a null cardinality.  Needed for storing Cardinality
  // objects in STL containers.
  Cardinality() {}
  // Constructs a Cardinality from its implementation.
  explicit Cardinality(const CardinalityInterface* impl) : impl_(impl) {}
  // Conservative estimate on the lower/upper bound of the number of
  // calls allowed.
  int ConservativeLowerBound() const { return impl_->ConservativeLowerBound(); }
  int ConservativeUpperBound() const { return impl_->ConservativeUpperBound(); }
  // Returns true if and only if call_count calls will satisfy this
  // cardinality.
  bool IsSatisfiedByCallCount(int call_count) const {
    return impl_->IsSatisfiedByCallCount(call_count);
  }
  // Returns true if and only if call_count calls will saturate this
  // cardinality.
  bool IsSaturatedByCallCount(int call_count) const {
    return impl_->IsSaturatedByCallCount(call_count);
  }
  // Returns true if and only if call_count calls will over-saturate this
  // cardinality, i.e. exceed the maximum number of allowed calls.
  bool IsOverSaturatedByCallCount(int call_count) const {
    return impl_->IsSaturatedByCallCount(call_count) &&
        !impl_->IsSatisfiedByCallCount(call_count);
  }
  // Describes self to an ostream
  void DescribeTo(::std::ostream* os) const { impl_->DescribeTo(os); }
  // Describes the given actual call count to an ostream.
  static void DescribeActualCallCountTo(int actual_call_count,
                                        ::std::ostream* os);
 private:
  std::shared_ptr<const CardinalityInterface> impl_;
};
// Creates a cardinality that allows at least n calls.
GTEST_API_ Cardinality AtLeast(int n);
// Creates a cardinality that allows at most n calls.
GTEST_API_ Cardinality AtMost(int n);
// Creates a cardinality that allows any number of calls.
GTEST_API_ Cardinality AnyNumber();
// Creates a cardinality that allows between min and max calls.
GTEST_API_ Cardinality Between(int min, int max);
// Creates a cardinality that allows exactly n calls.
GTEST_API_ Cardinality Exactly(int n);
// Creates a cardinality from its implementation.
inline Cardinality MakeCardinality(const CardinalityInterface* c) {
  return Cardinality(c);
}
}  // namespace testing
References testing::internal::Apply(), testing::internal::ArrayAwareFind(), testing::internal::Assert(), testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::Base64Unescape(), bool, testing::internal::String::CaseInsensitiveCStringEquals(), testing::internal::String::CaseInsensitiveWideCStringEquals(), testing::DoDefault(), testing::internal::EndsWith(), testing::internal::Expect(), false, testing::internal::FormatFileLocation(), testing::internal::RE::FullMatch(), testing::internal::GetRawPointer(), testing::internal::GetTypeName(), GMOCK_KIND_OF_, GTEST_API_, GTEST_ATTRIBUTE_UNUSED_, GTEST_CHECK_, GTEST_COMPILE_ASSERT_, GTEST_DECLARE_STATIC_MUTEX_, GTEST_DISALLOW_ASSIGN_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_EXCLUSIVE_LOCK_REQUIRED_, GTEST_LOCK_EXCLUDED_, GTEST_LOG_, GTEST_REMOVE_REFERENCE_AND_CONST_, GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_, testing::Invoke(), testing::internal::kInfo, testing::internal::kOther, testing::internal::kWarning, testing::internal::Log(), testing::internal::operator!=(), testing::operator<<(), testing::internal::operator==(), testing::internal::RE::PartialMatch(), testing::internal::UniversalPrinter< T >::Print(), testing::PrintToString(), testing::internal::StartsWith(), and testing::internal::UniversalPrint().