MUSI6106: CLfo Class Reference
CLfo Class Reference
#include <Lfo.h>
Public Types
enum LfoType_t { kSine , kSaw , kRect , kNumLfoTypes }
enum LfoParam_t { kLfoParamAmplitude , kLfoParamFrequency , kNumLfoParams }
Public Member Functions
CLfo (float fSampleRate)
virtual ~CLfo ()
Error_t setLfoType (LfoType_t eType)
Error_t setParam (LfoParam_t eParam, float fValue)
float getParam (LfoParam_t eParam) const
float getNext ()
Private Member Functions
void computeWaveTable ()
Private Attributes
float m_fSampleRate
float m_fReadIndex
float m_afParam [kNumLfoParams]
LfoType_t m_eType
CRingBuffer< float > * m_pCRingBuff
Static Private Attributes
static const int m_kiBufferLength = 4096
Detailed Description
Definition at line 11 of file Lfo.h.
Member Enumeration Documentation
LfoParam_t
enum CLfo::LfoParam_t
Enumerator
kLfoParamAmplitude
kLfoParamFrequency
kNumLfoParams
Definition at line 40 of file Lfo.h.
    {
        kLfoParamAmplitude,
        kLfoParamFrequency,
        kNumLfoParams
    };
LfoType_t
enum CLfo::LfoType_t
Enumerator
kSine
kSaw
kRect
kNumLfoTypes
Definition at line 32 of file Lfo.h.
    {
        kSine,
        kSaw,
        kRect,
        kNumLfoTypes
    };
Constructor & Destructor Documentation
CLfo()
CLfo::CLfo (float fSampleRate) inline
Definition at line 14 of file Lfo.h.
                            :
        m_fSampleRate(fSampleRate),
        m_fReadIndex(0),
        m_eType(kSine),
        m_pCRingBuff(0)
    {
        for (int i = 0; i < kNumLfoParams; i++)
            m_afParam[i]    = 0;
        m_pCRingBuff = new CRingBuffer<float>(m_kiBufferLength);
        setLfoType(kSine);
    }
References kNumLfoParams, kSine, m_afParam, m_kiBufferLength, m_pCRingBuff, and setLfoType().
~CLfo()
virtual CLfo::~CLfo () inline virtual
Definition at line 27 of file Lfo.h.
    {
        delete m_pCRingBuff;
    }
References m_pCRingBuff.
Member Function Documentation
computeWaveTable()
void CLfo::computeWaveTable () inline private
Definition at line 74 of file Lfo.h.
    {
        float *pfBuff = new float [m_kiBufferLength];
        switch (m_eType)
        {
        case kSine:
            CSynthesis::generateSine (pfBuff, 1.F, 1.F*m_kiBufferLength, m_kiBufferLength);
            break;
        case kSaw:
            CSynthesis::generateSaw (pfBuff, 1.F, 1.F*m_kiBufferLength, m_kiBufferLength);
            break;
        case kRect:
            CSynthesis::generateRect (pfBuff, 1.F, 1.F*m_kiBufferLength, m_kiBufferLength);
            break;
        }
        m_pCRingBuff->put(pfBuff, m_kiBufferLength);
        delete [] pfBuff;
    }
References CSynthesis::generateRect(), CSynthesis::generateSaw(), CSynthesis::generateSine(), kRect, kSaw, kSine, m_eType, m_kiBufferLength, m_pCRingBuff, and CRingBuffer< T >::put().
Referenced by setLfoType().
getNext()
float CLfo::getNext () inline
Definition at line 64 of file Lfo.h.
    {
        float fValue = m_afParam[kLfoParamAmplitude] * m_pCRingBuff->get(m_fReadIndex);
        m_fReadIndex = m_fReadIndex + m_afParam[kLfoParamFrequency]/m_fSampleRate * m_kiBufferLength;
        if (m_fReadIndex >= m_kiBufferLength)
            m_fReadIndex -= m_kiBufferLength;
        return fValue;
    }
References CRingBuffer< T >::get(), kLfoParamAmplitude, kLfoParamFrequency, m_afParam, m_fReadIndex, m_fSampleRate, m_kiBufferLength, and m_pCRingBuff.
Referenced by CVibrato::process().
getParam()
float CLfo::getParam (LfoParam_t eParam) const inline
Definition at line 59 of file Lfo.h.
    {
        return m_afParam[eParam];
    }
References m_afParam.
Referenced by CVibrato::getParam().
setLfoType()
Error_t CLfo::setLfoType (LfoType_t eType) inline
Definition at line 47 of file Lfo.h.
    {
        m_eType = eType;
        computeWaveTable();
        return Error_t::kNoError;
    }
References computeWaveTable(), kNoError, and m_eType.
Referenced by CLfo().
setParam()
Error_t CLfo::setParam (LfoParam_t eParam, float fValue) inline
Definition at line 53 of file Lfo.h.
    {
        m_afParam[eParam]   = fValue;
        return Error_t::kNoError;
    }
References kNoError, and m_afParam.
Referenced by CVibrato::setParam().
Member Data Documentation
m_afParam
float CLfo::m_afParam[kNumLfoParams] private
Definition at line 98 of file Lfo.h.
Referenced by CLfo(), getNext(), getParam(), and setParam().
m_eType
LfoType_t CLfo::m_eType private
Definition at line 100 of file Lfo.h.
Referenced by computeWaveTable(), and setLfoType().
m_fReadIndex
float CLfo::m_fReadIndex private
Definition at line 97 of file Lfo.h.
Referenced by getNext().
m_fSampleRate
float CLfo::m_fSampleRate private
Definition at line 96 of file Lfo.h.
Referenced by getNext().
m_kiBufferLength
const int CLfo::m_kiBufferLength = 4096 static private
Definition at line 94 of file Lfo.h.
Referenced by CLfo(), computeWaveTable(), and getNext().
m_pCRingBuff
CRingBuffer<float>* CLfo::m_pCRingBuff private
Definition at line 102 of file Lfo.h.
Referenced by CLfo(), computeWaveTable(), getNext(), and ~CLfo().
The documentation for this class was generated from the following file:
Lfo.h