MUSI6106: testing::DefaultValue< T > Class Template Reference
testing::DefaultValue< T > Class Template Reference
#include <gmock-actions.h>
Classes
class FactoryValueProducer
class FixedValueProducer
class ValueProducer
Public Types
typedef T(* FactoryFunction) ()
Static Public Member Functions
static void Set (T x)
static void SetFactory (FactoryFunction factory)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T Get ()
Static Private Attributes
static ValueProducer * producer_ = nullptr
Detailed Description
template<typename T>
class testing::DefaultValue< T >
Definition at line 285 of file gmock-actions.h.
Member Typedef Documentation
FactoryFunction
template<typename T > typedef T(* testing::DefaultValue< T >::FactoryFunction) ()
Definition at line 297 of file gmock-actions.h.
Member Function Documentation
Clear()
template<typename T > static void testing::DefaultValue< T >::Clear () inline static
Definition at line 304 of file gmock-actions.h.
                      {
    delete producer_;
    producer_ = nullptr;
  }
References testing::DefaultValue< T >::producer_.
Exists()
template<typename T > static bool testing::DefaultValue< T >::Exists () inline static
Definition at line 314 of file gmock-actions.h.
                       {
    return IsSet() || internal::BuiltInDefaultValue<T>::Exists();
  }
References testing::internal::BuiltInDefaultValue< T >::Exists(), and testing::DefaultValue< T >::IsSet().
Get()
template<typename T > static T testing::DefaultValue< T >::Get () inline static
Definition at line 321 of file gmock-actions.h.
                 {
    return producer_ == nullptr ? internal::BuiltInDefaultValue<T>::Get()
                                : producer_->Produce();
  }
References testing::internal::BuiltInDefaultValue< T >::Get(), testing::DefaultValue< T >::ValueProducer::Produce(), and testing::DefaultValue< T >::producer_.
IsSet()
template<typename T > static bool testing::DefaultValue< T >::IsSet () inline static
Definition at line 310 of file gmock-actions.h.
{ return producer_ != nullptr; }
References testing::DefaultValue< T >::producer_.
Referenced by testing::DefaultValue< T >::Exists().
Set()
template<typename T > static void testing::DefaultValue< T >::Set (T x) inline static
Definition at line 289 of file gmock-actions.h.
                       {
    delete producer_;
    producer_ = new FixedValueProducer(x);
  }
References testing::DefaultValue< T >::producer_.
SetFactory()
template<typename T > static void testing::DefaultValue< T >::SetFactory (FactoryFunction factory) inline static
Definition at line 298 of file gmock-actions.h.
{
    delete producer_;
    producer_ = new FactoryValueProducer(factory);
  }
References testing::DefaultValue< T >::producer_.
Member Data Documentation
producer_
template<typename T > DefaultValue< T >::ValueProducer * testing::DefaultValue< T >::producer_ = nullptr static private
Definition at line 354 of file gmock-actions.h.
Referenced by testing::DefaultValue< T >::Clear(), testing::DefaultValue< T >::Get(), testing::DefaultValue< T >::IsSet(), testing::DefaultValue< T >::Set(), and testing::DefaultValue< T >::SetFactory().
The documentation for this class was generated from the following file:
gmock-actions.h