MUSI6106: CFft Class Reference
CFft Class Reference
#include <Fft.h>
Public Types
enum WindowFunction_t { kWindowSine , kWindowHann , kWindowHamming , kNumWindows }
enum Windowing_t { kNoWindow = 0x00L , kPreWindow = 0x01L , kPostWindow = 0x02L }
enum Length_t {
kLengthFft , kLengthData , kLengthMagnitude , kLengthPhase ,
kNumLengths
}
typedef float complex_t
Public Member Functions
Error_t initInstance (int iBlockLength, int iZeroPadFactor=1, WindowFunction_t eWindow=kWindowHann, Windowing_t eWindowing=kPreWindow)
Error_t resetInstance ()
Error_t overrideWindow (const float *pfNewWindow)
Error_t getWindow (float *pfWindow) const
Error_t doFft (complex_t *pfSpectrum, const float *pfInput)
Error_t doInvFft (float *pfOutput, const complex_t *pfSpectrum)
Error_t getMagnitude (float *pfMag, const complex_t *pfSpectrum) const
Error_t getPhase (float *pfPhase, const complex_t *pfSpectrum) const
Error_t splitRealImag (float *pfReal, float *pfImag, const complex_t *pfSpectrum) const
Error_t mergeRealImag (complex_t *pfSpectrum, const float *pfReal, const float *pfImag) const
int getLength (Length_t eLengthIdx)
float freq2bin (float fFreqInHz, float fSampleRateInHz) const
float bin2freq (int iBinIdx, float fSampleRateInHz) const
Static Public Member Functions
static Error_t createInstance (CFft *&pCFft)
static Error_t destroyInstance (CFft *&pCFft)
Protected Member Functions
CFft ()
virtual ~CFft ()
Private Member Functions
Error_t allocMemory ()
Error_t freeMemory ()
Error_t computeWindow (WindowFunction_t eWindow)
Private Attributes
float * m_pfProcessBuff
float * m_pfWindowBuff
int m_iDataLength
int m_iFftLength
Windowing_t m_ePrePostWindowOpt
bool m_bIsInitialized
Static Private Attributes
static const float m_Pi = static_cast<float>(M_PI)
static const float m_Pi2 = static_cast<float>(M_PI_2)
Detailed Description
Definition at line 6 of file Fft.h.
Member Typedef Documentation
complex_t
typedef float CFft::complex_t
Definition at line 9 of file Fft.h.
Member Enumeration Documentation
Length_t
enum CFft::Length_t
Enumerator
kLengthFft
length of the FFT
kLengthData
length of the input data
kLengthMagnitude
length of the magnitude spectrum
kLengthPhase
length of the phase spectrum
kNumLengths
Definition at line 105 of file Fft.h.
    {
        kLengthFft,             //!< length of the FFT
        kLengthData,            //!< length of the input data
        kLengthMagnitude,       //!< length of the magnitude spectrum
        kLengthPhase,           //!< length of the phase spectrum
        kNumLengths
    };
WindowFunction_t
enum CFft::WindowFunction_t
defines the window function to use – a custom window can also be used (
See also
overrideWindow)
Enumerator
kWindowSine
sinusoidal window
kWindowHann
von-Hann window
kWindowHamming
Hamming window.
kNumWindows
Definition at line 12 of file Fft.h.
    {
        //kWindowNone,            //!< rectangular window (see Windowing_t::kNoWindow)
        kWindowSine,            //!< sinusoidal window
        kWindowHann,            //!< von-Hann window
        kWindowHamming,         //!< Hamming window
        kNumWindows
    };
Windowing_t
enum CFft::Windowing_t
Enumerator
kNoWindow
do not apply any window
kPreWindow
apply window function before FFT
kPostWindow
apply window function after IFFT
Definition at line 21 of file Fft.h.
    {
        kNoWindow   = 0x00L,    //!< do not apply any window
        kPreWindow  = 0x01L,    //!< apply window function before FFT
        kPostWindow = 0x02L     //!< apply window function after IFFT
    };
Constructor & Destructor Documentation
CFft()
CFft::CFft () protected
Definition at line 14 of file Fft.cpp.
           :
    m_pfProcessBuff(0),
    m_pfWindowBuff(0),
    m_iDataLength(0),
    m_iFftLength(0),
    m_ePrePostWindowOpt(kNoWindow),
    m_bIsInitialized(false)
{
    resetInstance ();
}
References resetInstance().
Referenced by createInstance().
~CFft()
virtual CFft::~CFft () inline protected virtual
Definition at line 135 of file Fft.h.
{};
Member Function Documentation
allocMemory()
Error_t CFft::allocMemory () private
Definition at line 245 of file Fft.cpp.
{
    m_pfProcessBuff = new float [m_iFftLength];
    m_pfWindowBuff  = new float [m_iDataLength];
    if (!m_pfProcessBuff || !m_pfWindowBuff)
        return Error_t::kMemError;
    else
    {
        return Error_t::kNoError;
    }
}
References kMemError, kNoError, m_iDataLength, m_iFftLength, m_pfProcessBuff, and m_pfWindowBuff.
Referenced by initInstance().
bin2freq()
float CFft::bin2freq (int iBinIdx, float fSampleRateInHz) const
convert bin to frequency
Parameters
int iBinIdx: index of the FFT bin
float fSampleRateInHz: sample rate of the audio signal
Returns
float: frequency in Hz
Definition at line 240 of file Fft.cpp.
{
    return iBinIdx * fSampleRateInHz / m_iFftLength;
}
References m_iFftLength.
computeWindow()
Error_t CFft::computeWindow (WindowFunction_t eWindow) private
Definition at line 270 of file Fft.cpp.
{
    int i;
    // note that these windows are periodic, not symmetric
    switch (eWindow)
    {
    case kWindowSine:
        {
            for (i = 0; i < m_iDataLength; i++)
            {
                m_pfWindowBuff[i]   = sinf((i * m_Pi) / (m_iDataLength+1));
            }
            break;
        }
    case kWindowHann:
        {
            for (i = 0; i < m_iDataLength; i++)
            {
                m_pfWindowBuff[i]   = .5F * (1.F - cosf((i * 2.F*m_Pi) / (m_iDataLength+1)));
            }
            break;
        }
    case kWindowHamming:
        {
            for (i = 0; i < m_iDataLength; i++)
            {
                m_pfWindowBuff[i]   = .54F - .46F * cosf((i * 2.F*m_Pi) / (m_iDataLength+1));
            }
            break;
        }
    }
    return Error_t::kNoError;
}
References kNoError, kWindowHamming, kWindowHann, kWindowSine, m_iDataLength, m_pfWindowBuff, and m_Pi.
Referenced by initInstance().
createInstance()
Error_t CFft::createInstance (CFft *& pCFft) static
creates a new FFT instance
Parameters
CFft * & pCFft: pointer to the new instance
Returns
Error_t
Definition at line 25 of file Fft.cpp.
{
    pCFft = new CFft ();
    if (!pCFft)
        return Error_t::kMemError;
    return Error_t::kNoError;
}
References CFft(), kMemError, and kNoError.
Referenced by main().
destroyInstance()
Error_t CFft::destroyInstance (CFft *& pCFft) static
destroys and FFT instance
Parameters
CFft * & pCFft: pointer to the instance to be destroyed
Returns
Error_t
Definition at line 35 of file Fft.cpp.
{
    if (!pCFft)
        return Error_t::kNoError;
    delete pCFft;
    pCFft   = 0;
    return Error_t::kNoError;
}
References kNoError.
Referenced by main().
doFft()
Error_t CFft::doFft (complex_t * pfSpectrum, const float * pfInput)
perform the FFT
Parameters
complex_t * pfSpectrum: output result of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Parameters
const float * pfInput: input data of length iBlockLength (
See also
initInstance)
Returns
Error_t
Definition at line 111 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!pfInput || !pfSpectrum)
        return Error_t::kFunctionInvalidArgsError;
    // copy data to internal buffer
    CVectorFloat::copy(m_pfProcessBuff, pfInput, m_iDataLength);
    CVectorFloat::setZero(&m_pfProcessBuff[m_iDataLength], m_iFftLength-m_iDataLength);
    // apply window function
    if (m_ePrePostWindowOpt & kPreWindow)
        CVectorFloat::mul_I(m_pfProcessBuff, m_pfWindowBuff, m_iDataLength);
    // compute fft
    LaszloFft::realfft_split(m_pfProcessBuff, m_iFftLength);
    // copy data to output buffer
    CVectorFloat::copy(pfSpectrum, m_pfProcessBuff, m_iFftLength);
    return Error_t::kNoError;
}
References CVectorFloat::copy(), kFunctionInvalidArgsError, kNoError, kNotInitializedError, kPreWindow, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, m_iFftLength, m_pfProcessBuff, m_pfWindowBuff, CVectorFloat::mul_I(), LaszloFft::realfft_split(), and CVectorFloat::setZero().
Referenced by main().
doInvFft()
Error_t CFft::doInvFft (float * pfOutput, const complex_t * pfSpectrum)
perform IFFT
Parameters
float * pfOutput: time domain output signal of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Parameters
const complex_t * pfSpectrum: input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 135 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // copy data to internal buffer
    CVectorFloat::copy(m_pfProcessBuff, pfSpectrum, m_iFftLength);
    // compute ifft
    LaszloFft::irealfft_split(m_pfProcessBuff, m_iFftLength);
    // apply window function
    if (m_ePrePostWindowOpt & kPostWindow)
        CVectorFloat::mul_I(m_pfProcessBuff, m_pfWindowBuff, m_iDataLength);
    // copy data to output buffer
    CVectorFloat::copy(pfOutput, m_pfProcessBuff, m_iFftLength);
    return Error_t::kNoError;
}
References CVectorFloat::copy(), LaszloFft::irealfft_split(), kNoError, kNotInitializedError, kPostWindow, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, m_iFftLength, m_pfProcessBuff, m_pfWindowBuff, and CVectorFloat::mul_I().
freeMemory()
Error_t CFft::freeMemory () private
Definition at line 259 of file Fft.cpp.
{
    delete [] m_pfProcessBuff;
    delete [] m_pfWindowBuff;
    m_pfProcessBuff = 0;
    m_pfWindowBuff  = 0;
    return Error_t::kNoError;
}
References kNoError, m_pfProcessBuff, and m_pfWindowBuff.
Referenced by resetInstance().
freq2bin()
float CFft::freq2bin (float fFreqInHz, float fSampleRateInHz) const
convert frequency to bin value
Parameters
float fFreqInHz: frequency to convert
float fSampleRateInHz: sample rate of the audio signal
Returns
float: index (not quantized to integer)
Definition at line 235 of file Fft.cpp.
{
    return fFreqInHz / fSampleRateInHz * m_iFftLength;
}
References m_iFftLength.
getLength()
int CFft::getLength (Length_t eLengthIdx)
return length of spectrum
Parameters
Length_t eLengthIdx spectrum type
Returns
int
Definition at line 306 of file Fft.cpp.
{
    switch (eLengthIdx)
    {
    case kLengthFft:
        return m_iFftLength;
    case kLengthData:
        return m_iDataLength;
    case kLengthMagnitude:
    case kLengthPhase:
        return m_iFftLength/2+1;
    }
    return 0;
}
References kLengthData, kLengthFft, kLengthMagnitude, kLengthPhase, m_iDataLength, and m_iFftLength.
getMagnitude()
Error_t CFft::getMagnitude (float * pfMag, const complex_t * pfSpectrum) const
extract magnitude spectrum from complex values
Parameters
float * pfMag: resulting magnitude spectrum of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
const complex_t * pfSpectrum: input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 156 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    // no imaginary part at these bins
    pfMag[0]        = std::abs(pfSpectrum[0]);
    pfMag[iNyq]     = std::abs(pfSpectrum[iNyq]);
    for (int i = 1; i < iNyq; i++)
    {
        int iImagIdx    = m_iFftLength - i;
        pfMag[i]        = sqrtf(pfSpectrum[i]*pfSpectrum[i] + pfSpectrum[iImagIdx]*pfSpectrum[iImagIdx]);
    }
    return Error_t::kNoError;
}
References kNoError, kNotInitializedError, m_bIsInitialized, and m_iFftLength.
Referenced by main().
getPhase()
Error_t CFft::getPhase (float * pfPhase, const complex_t * pfSpectrum) const
extract phase spectrum from complex values
Parameters
float * pfPhase: resulting phase spectrum of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
const complex_t * pfSpectrum: input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 176 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    pfPhase[0]      = m_Pi;
    pfPhase[iNyq]   = m_Pi;
    for (int i = 1; i < iNyq; i++)
    {
        int iImagIdx    = m_iFftLength - i;
        if (pfSpectrum[i] == .0F && pfSpectrum[iImagIdx] != .0F)
            pfPhase[i]   = m_Pi2;
        else
            pfPhase[i]   = atan2f (pfSpectrum[iImagIdx], pfSpectrum[i]);
    }
    return Error_t::kNoError;
}
References kNoError, kNotInitializedError, m_bIsInitialized, m_iFftLength, m_Pi, and m_Pi2.
getWindow()
Error_t CFft::getWindow (float * pfWindow) const
retrieve current window
Parameters
float * pfWindow: window data of length iBlockLength (
See also
initInstance)
Returns
Error_t
Definition at line 99 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!pfWindow)
        return Error_t::kFunctionInvalidArgsError;
    CVectorFloat::copy(pfWindow, m_pfWindowBuff, m_iDataLength);
    return Error_t::kNoError;
}
References CVectorFloat::copy(), kFunctionInvalidArgsError, kNoError, kNotInitializedError, m_bIsInitialized, m_iDataLength, and m_pfWindowBuff.
initInstance()
Error_t CFft::initInstance (int iBlockLength, int iZeroPadFactor = 1, WindowFunction_t eWindow = kWindowHann, Windowing_t eWindowing = kPreWindow)
initializes an FFT instance
Parameters
int iBlockLength: input data block length in Frames
int iZeroPadFactor: fft length (zeropadded)
WindowFunction_t eWindow: window type
Windowing_t eWindowing: apply window before FFT, after IFFT, or both
Returns
Error_t
Definition at line 46 of file Fft.cpp.
{
    Error_t  rErr = Error_t::kNoError;
    // sanity check
    if (!CUtil::isPowOf2(iBlockLength) || iZeroPadFactor <= 0 || !CUtil::isPowOf2(iBlockLength*iZeroPadFactor))
        return Error_t::kFunctionInvalidArgsError;
    // clean up
    resetInstance();
    m_iDataLength   = iBlockLength;
    m_iFftLength    = iBlockLength * iZeroPadFactor;
    m_ePrePostWindowOpt = eWindowing;
    rErr = allocMemory ();
    if (rErr != Error_t::kNoError)
        return rErr;
    rErr = computeWindow (eWindow);
    m_bIsInitialized    = true;
    return rErr;
}
References allocMemory(), computeWindow(), CUtil::isPowOf2(), kFunctionInvalidArgsError, kNoError, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, m_iFftLength, and resetInstance().
Referenced by main().
mergeRealImag()
Error_t CFft::mergeRealImag (complex_t * pfSpectrum, const float * pfReal, const float * pfImag) const
merge real and imaginary parts into complex spectrum
Parameters
complex_t * pfSpectrum: resulting spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Parameters
const float * pfReal: input real part of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
const float * pfImag: input imaginary part of length (iBlockLength * iZeroPadFactor)/2 (
See also
initInstance)
Returns
Error_t
Definition at line 217 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    CVectorFloat::copy(pfSpectrum, pfReal, iNyq+1);
    for (int i = 1, iImag = m_iFftLength-1; i < iNyq-1; i++, iImag--)
    {
        pfSpectrum[iImag]   = pfImag[i];
    }
    return Error_t::kNoError;
}
References CVectorFloat::copy(), kNoError, kNotInitializedError, m_bIsInitialized, and m_iFftLength.
overrideWindow()
Error_t CFft::overrideWindow (const float * pfNewWindow)
use a customized window
Parameters
const float * pfNewWindow: window data of length iBlockLength (
See also
initInstance)
Returns
Error_t
Definition at line 87 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!pfNewWindow)
        return Error_t::kFunctionInvalidArgsError;
    CVectorFloat::copy(m_pfWindowBuff, pfNewWindow, m_iDataLength);
    return Error_t::kNoError;
}
References CVectorFloat::copy(), kFunctionInvalidArgsError, kNoError, kNotInitializedError, m_bIsInitialized, m_iDataLength, and m_pfWindowBuff.
resetInstance()
Error_t CFft::resetInstance ()
resets an FFT instance
Returns
Error_t
Definition at line 73 of file Fft.cpp.
{
    freeMemory();
    m_iDataLength       = 0;
    m_iFftLength        = 0;
    m_ePrePostWindowOpt = kNoWindow;
    m_bIsInitialized    = false;
    return Error_t::kNoError;
}
References freeMemory(), kNoError, kNoWindow, m_bIsInitialized, m_ePrePostWindowOpt, m_iDataLength, and m_iFftLength.
Referenced by CFft(), and initInstance().
splitRealImag()
Error_t CFft::splitRealImag (float * pfReal, float * pfImag, const complex_t * pfSpectrum) const
get real and imaginary part from complex spectrum
Parameters
float * pfReal: resulting real part of length (iBlockLength * iZeroPadFactor)/2+1 (
See also
initInstance)
Parameters
float * pfImag: resulting imaginary part of length (iBlockLength * iZeroPadFactor)/2 (
See also
initInstance)
Parameters
const complex_t * pfSpectrum: input spectrum of length iBlockLength * iZeroPadFactor (
See also
initInstance)
Returns
Error_t
Definition at line 198 of file Fft.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    // re(0),re(1),re(2),...,re(size/2),im(size/2-1),...,im(1)
    int iNyq        = m_iFftLength>>1;
    CVectorFloat::copy(pfReal, pfSpectrum, iNyq+1);
    pfImag[0]       = 0;
    for (int i = 1, iImag = m_iFftLength-1; i < iNyq; i++, iImag--)
    {
        pfImag[i]   = pfSpectrum[iImag];
    }
    return Error_t::kNoError;
}
References CVectorFloat::copy(), kNoError, kNotInitializedError, m_bIsInitialized, and m_iFftLength.
Member Data Documentation
m_bIsInitialized
bool CFft::m_bIsInitialized private
Definition at line 150 of file Fft.h.
Referenced by doFft(), doInvFft(), getMagnitude(), getPhase(), getWindow(), initInstance(), mergeRealImag(), overrideWindow(), resetInstance(), and splitRealImag().
m_ePrePostWindowOpt
Windowing_t CFft::m_ePrePostWindowOpt private
Definition at line 148 of file Fft.h.
Referenced by doFft(), doInvFft(), initInstance(), and resetInstance().
m_iDataLength
int CFft::m_iDataLength private
Definition at line 145 of file Fft.h.
Referenced by allocMemory(), computeWindow(), doFft(), doInvFft(), getLength(), getWindow(), initInstance(), overrideWindow(), and resetInstance().
m_iFftLength
int CFft::m_iFftLength private
Definition at line 146 of file Fft.h.
Referenced by allocMemory(), bin2freq(), doFft(), doInvFft(), freq2bin(), getLength(), getMagnitude(), getPhase(), initInstance(), mergeRealImag(), resetInstance(), and splitRealImag().
m_pfProcessBuff
float* CFft::m_pfProcessBuff private
Definition at line 142 of file Fft.h.
Referenced by allocMemory(), doFft(), doInvFft(), and freeMemory().
m_pfWindowBuff
float* CFft::m_pfWindowBuff private
Definition at line 143 of file Fft.h.
Referenced by allocMemory(), computeWindow(), doFft(), doInvFft(), freeMemory(), getWindow(), and overrideWindow().
m_Pi
const float CFft::m_Pi = static_cast<float>(M_PI) static private
Definition at line 152 of file Fft.h.
Referenced by computeWindow(), and getPhase().
m_Pi2
const float CFft::m_Pi2 = static_cast<float>(M_PI_2) static private
Definition at line 153 of file Fft.h.
Referenced by getPhase().
The documentation for this class was generated from the following files:
Fft.h
Fft.cpp