MUSI6106: CVibrato Class Reference
CVibrato Class Reference
#include <Vibrato.h>
Public Types
enum Version_t { kMajor , kMinor , kPatch , kNumVersionInts }
enum VibratoParam_t { kParamModWidthInS , kParamModFreqInHz , kNumVibratoParams }
Public Member Functions
Error_t init (float fMaxModWidthInS, float fSampleRateInHz, int iNumChannels)
Error_t reset ()
Error_t setParam (VibratoParam_t eParam, float fParamValue)
float getParam (VibratoParam_t eParam) const
Error_t process (float **ppfInputBuffer, float **ppfOutputBuffer, int iNumberOfFrames)
Static Public Member Functions
static const int getVersion (const Version_t eVersionIdx)
static const char * getBuildDate ()
static Error_t create (CVibrato *&pCVibrato)
static Error_t destroy (CVibrato *&pCVibrato)
Protected Member Functions
CVibrato ()
virtual ~CVibrato ()
Private Member Functions
bool isInParamRange (VibratoParam_t eParam, float fValue)
Private Attributes
bool m_bIsInitialized
CLfo * m_pCLfo
CRingBuffer< float > ** m_ppCRingBuff
float m_fSampleRate
int m_iNumChannels
float m_aafParamRange [kNumVibratoParams][2]
Detailed Description
Definition at line 10 of file Vibrato.h.
Member Enumeration Documentation
Version_t
enum CVibrato::Version_t
version number
Enumerator
kMajor
major version number
kMinor
minor version number
kPatch
patch version number
kNumVersionInts
Definition at line 14 of file Vibrato.h.
    {
        kMajor, //!< major version number
        kMinor, //!< minor version number
        kPatch, //!< patch version number
        kNumVersionInts
    };
VibratoParam_t
enum CVibrato::VibratoParam_t
Enumerator
kParamModWidthInS
kParamModFreqInHz
kNumVibratoParams
Definition at line 23 of file Vibrato.h.
    {
        kParamModWidthInS,
        kParamModFreqInHz,
        kNumVibratoParams
    };
Constructor & Destructor Documentation
CVibrato()
CVibrato::CVibrato () protected
Definition at line 17 of file Vibrato.cpp.
                    :
    m_bIsInitialized(false),
    m_pCLfo(0),
    m_ppCRingBuff(0),
    m_fSampleRate(44100),
    m_iNumChannels(0)
{
    // this never hurts
    this->reset ();
}
References reset().
Referenced by create().
~CVibrato()
CVibrato::~CVibrato () protected virtual
Definition at line 30 of file Vibrato.cpp.
{
    this->reset ();
}
References reset().
Member Function Documentation
create()
Error_t CVibrato::create (CVibrato *& pCVibrato) static
Definition at line 62 of file Vibrato.cpp.
{
    pCVibrato = new CVibrato ();
    if (!pCVibrato)
        return Error_t::kUnknownError;
    return Error_t::kNoError;
}
References CVibrato(), kNoError, and kUnknownError.
Referenced by main().
destroy()
Error_t CVibrato::destroy (CVibrato *& pCVibrato) static
Definition at line 73 of file Vibrato.cpp.
{
    if (!pCVibrato)
        return Error_t::kUnknownError;
    pCVibrato->reset ();
    delete pCVibrato;
    pCVibrato = 0;
    return Error_t::kNoError;
}
References kNoError, kUnknownError, and reset().
Referenced by main().
getBuildDate()
const char * CVibrato::getBuildDate () static
Definition at line 57 of file Vibrato.cpp.
{
    return kCVibratoBuildDate;
}
References kCVibratoBuildDate.
getParam()
float CVibrato::getParam (VibratoParam_t eParam) const
Definition at line 153 of file Vibrato.cpp.
{
    switch (eParam)
    {
    case kParamModFreqInHz:
        return m_pCLfo->getParam(CLfo::kLfoParamFrequency);
    case kParamModWidthInS:
        return m_pCLfo->getParam(CLfo::kLfoParamAmplitude) / m_fSampleRate;
    }
    return 0;
}
References CLfo::getParam(), CLfo::kLfoParamAmplitude, CLfo::kLfoParamFrequency, kParamModFreqInHz, kParamModWidthInS, m_fSampleRate, and m_pCLfo.
getVersion()
const int CVibrato::getVersion (const Version_t eVersionIdx) static
Definition at line 35 of file Vibrato.cpp.
{
    int iVersion = 0;
    switch (eVersionIdx)
    {
    case kMajor:
        iVersion    = MUSI6106_VERSION_MAJOR;
        break;
    case kMinor:
        iVersion    = MUSI6106_VERSION_MINOR;
        break;
    case kPatch:
        iVersion    = MUSI6106_VERSION_PATCH;
        break;
    case kNumVersionInts:
        iVersion    = -1;
        break;
    }
    return iVersion;
}
References kMajor, kMinor, kNumVersionInts, kPatch, MUSI6106_VERSION_MAJOR, MUSI6106_VERSION_MINOR, and MUSI6106_VERSION_PATCH.
init()
Error_t CVibrato::init (float fMaxModWidthInS, float fSampleRateInHz, int iNumChannels)
Definition at line 87 of file Vibrato.cpp.
{
    // set parameters
    m_fSampleRate       = fSampleRateInHz;
    m_iNumChannels      = iNumChannels;
    // set parameter ranges
    m_aafParamRange[kParamModFreqInHz][0] = 0;
    m_aafParamRange[kParamModFreqInHz][1] = fSampleRateInHz*.5F;
    m_aafParamRange[kParamModWidthInS][0] = 0;
    m_aafParamRange[kParamModWidthInS][1] = fMaxModWidthInS;
    // create instances
    m_ppCRingBuff       = new CRingBuffer<float>*[m_iNumChannels];
    for (int c= 0; c < m_iNumChannels; c++)
    {
        m_ppCRingBuff[c]= new CRingBuffer<float>(CUtil::float2int<int>(fMaxModWidthInS*m_fSampleRate*2+1));
        m_ppCRingBuff[c]->setWriteIdx(CUtil::float2int<int>(fMaxModWidthInS*m_fSampleRate+1));
    }
    m_pCLfo             = new CLfo(m_fSampleRate);
    m_bIsInitialized    = true;
    return Error_t::kNoError;
}
References kNoError, kParamModFreqInHz, kParamModWidthInS, m_aafParamRange, m_bIsInitialized, m_fSampleRate, m_iNumChannels, m_pCLfo, m_ppCRingBuff, and CRingBuffer< T >::setWriteIdx().
Referenced by main().
isInParamRange()
bool CVibrato::isInParamRange (VibratoParam_t eParam, float fValue) private
Definition at line 166 of file Vibrato.cpp.
{
    if (fValue < m_aafParamRange[eParam][0] || fValue > m_aafParamRange[eParam][1])
    {
        return false;
    }
    else
    {
        return true;
    }
}
References m_aafParamRange.
Referenced by setParam().
process()
Error_t CVibrato::process (float ** ppfInputBuffer, float ** ppfOutputBuffer, int iNumberOfFrames)
Definition at line 178 of file Vibrato.cpp.
{
    if (!ppfInputBuffer || !ppfOutputBuffer || iNumberOfFrames < 0)
        return Error_t::kFunctionInvalidArgsError;
    for (int i = 0; i < iNumberOfFrames; i++)
    {
        float fOffset = m_pCLfo->getNext();
        for (int c = 0; c < m_iNumChannels; c++)
        {
            m_ppCRingBuff[c]->putPostInc(ppfInputBuffer[c][i]);
            ppfOutputBuffer[c][i]   = m_ppCRingBuff[c]->get(fOffset);
            m_ppCRingBuff[c]->getPostInc(); // dummy call to keep write and read idx in sync
        }
    }
    return Error_t::kNoError;
}
References CRingBuffer< T >::get(), CLfo::getNext(), CRingBuffer< T >::getPostInc(), kFunctionInvalidArgsError, kNoError, m_iNumChannels, m_pCLfo, m_ppCRingBuff, and CRingBuffer< T >::putPostInc().
Referenced by main().
reset()
Error_t CVibrato::reset ()
Definition at line 115 of file Vibrato.cpp.
{
    for (int i = 0; i < kNumVibratoParams; i++)
        setParam((VibratoParam_t)i, 0);
    for (int c= 0; c < m_iNumChannels; c++)
        delete m_ppCRingBuff[c];
    delete [] m_ppCRingBuff;
    m_ppCRingBuff       = 0;
    delete m_pCLfo;
    m_pCLfo             = 0;
    m_iNumChannels      = 0;
    m_bIsInitialized    = false;
    return Error_t::kNoError;
}
References kNoError, kNumVibratoParams, m_bIsInitialized, m_iNumChannels, m_pCLfo, m_ppCRingBuff, and setParam().
Referenced by CVibrato(), destroy(), and ~CVibrato().
setParam()
Error_t CVibrato::setParam (VibratoParam_t eParam, float fParamValue)
Definition at line 133 of file Vibrato.cpp.
{
    if (!m_bIsInitialized)
        return Error_t::kNotInitializedError;
    if (!isInParamRange(eParam, fParamValue))
        return Error_t::kFunctionInvalidArgsError;
    switch (eParam)
    {
    case kParamModFreqInHz:
        return m_pCLfo->setParam(CLfo::kLfoParamFrequency, fParamValue);
    case kParamModWidthInS:
        return m_pCLfo->setParam(CLfo::kLfoParamAmplitude, fParamValue * m_fSampleRate);
    case kNumVibratoParams:
        return Error_t::kFunctionInvalidArgsError;
    }
    return Error_t::kNoError;
}
References isInParamRange(), kFunctionInvalidArgsError, CLfo::kLfoParamAmplitude, CLfo::kLfoParamFrequency, kNoError, kNotInitializedError, kNumVibratoParams, kParamModFreqInHz, kParamModWidthInS, m_bIsInitialized, m_fSampleRate, m_pCLfo, and CLfo::setParam().
Referenced by main(), and reset().
Member Data Documentation
m_aafParamRange
float CVibrato::m_aafParamRange[kNumVibratoParams][2] private
Definition at line 58 of file Vibrato.h.
Referenced by init(), and isInParamRange().
m_bIsInitialized
bool CVibrato::m_bIsInitialized private
Definition at line 51 of file Vibrato.h.
Referenced by init(), reset(), and setParam().
m_fSampleRate
float CVibrato::m_fSampleRate private
Definition at line 56 of file Vibrato.h.
Referenced by getParam(), init(), and setParam().
m_iNumChannels
int CVibrato::m_iNumChannels private
Definition at line 57 of file Vibrato.h.
Referenced by init(), process(), and reset().
m_pCLfo
CLfo* CVibrato::m_pCLfo private
Definition at line 53 of file Vibrato.h.
Referenced by getParam(), init(), process(), reset(), and setParam().
m_ppCRingBuff
CRingBuffer<float>** CVibrato::m_ppCRingBuff private
Definition at line 54 of file Vibrato.h.
Referenced by init(), process(), and reset().
The documentation for this class was generated from the following files:
Vibrato.h
Vibrato.cpp