MUSI6106: testing::internal::BuiltInDefaultValue< T > Class Template Reference
testing::internal::BuiltInDefaultValue< T > Class Template Reference
#include <gmock-actions.h>
Static Public Member Functions
static bool Exists ()
static T Get ()
Detailed Description
template<typename T>
class testing::internal::BuiltInDefaultValue< T >
Definition at line 193 of file gmock-actions.h.
Member Function Documentation
Exists()
template<typename T > static bool testing::internal::BuiltInDefaultValue< T >::Exists () inline static
Definition at line 197 of file gmock-actions.h.
                       {
    return ::std::is_default_constructible<T>::value;
  }
Referenced by testing::internal::BuiltInDefaultValue< const T >::Exists(), testing::DefaultValue< T >::Exists(), and testing::DefaultValue< T & >::Exists().
Get()
template<typename T > static T testing::internal::BuiltInDefaultValue< T >::Get () inline static
Definition at line 201 of file gmock-actions.h.
                 {
    return BuiltInDefaultValueGetter<
        T, ::std::is_default_constructible<T>::value>::Get();
  }
References testing::internal::BuiltInDefaultValue< T >::Get().
Referenced by testing::internal::BuiltInDefaultValue< T >::Get(), testing::internal::BuiltInDefaultValue< const T >::Get(), testing::DefaultValue< T >::Get(), and testing::DefaultValue< T & >::Get().
The documentation for this class was generated from the following file:
gmock-actions.h