MUSI6106: testing::Action< F > Class Template Reference
testing::Action< F > Class Template Reference
#include <gmock-actions.h>
Classes
struct ActionAdapter
struct IgnoreArgs
Public Types
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Public Member Functions
Action ()
template<typename G , typename = typename std::enable_if<internal::disjunction< IsCompatibleFunctor<G>, std::is_constructible<std::function<Result()>, G>>::value>::type>
Action (G &&fun)
Action (ActionInterface< F > *impl)
template<typename Func >
Action (const Action< Func > &action)
bool IsDoDefault () const
Result Perform (ArgumentTuple args) const
Private Types
template<typename G >
using IsCompatibleFunctor = std::is_constructible< std::function< F >, G >
Private Member Functions
template<typename G >
void Init (G &&g, ::std::true_type)
template<typename G >
void Init (G &&g, ::std::false_type)
Private Attributes
::std::function< F > fun_
Friends
template<typename G >
class Action
Detailed Description
template<typename F>
class testing::Action< F >
Definition at line 436 of file gmock-actions.h.
Member Typedef Documentation
ArgumentTuple
template<typename F > typedef internal::Function<F>::ArgumentTuple testing::Action< F >::ArgumentTuple
Definition at line 455 of file gmock-actions.h.
IsCompatibleFunctor
template<typename F > template<typename G > using testing::Action< F >::IsCompatibleFunctor = std::is_constructible<std::function<F>, G> private
Definition at line 451 of file gmock-actions.h.
Result
template<typename F > typedef internal::Function<F>::Result testing::Action< F >::Result
Definition at line 454 of file gmock-actions.h.
Constructor & Destructor Documentation
Action() [1/4]
template<typename F > testing::Action< F >::Action () inline
Definition at line 459 of file gmock-actions.h.
{}
Action() [2/4]
template<typename F > template<typename G , typename = typename std::enable_if<internal::disjunction< IsCompatibleFunctor<G>, std::is_constructible<std::function<Result()>, G>>::value>::type> testing::Action< F >::Action (G && fun) inline
Definition at line 469 of file gmock-actions.h.
                  {  // NOLINT
    Init(::std::forward<G>(fun), IsCompatibleFunctor<G>());
  }
References testing::Action< F >::Init().
Action() [3/4]
template<typename F > testing::Action< F >::Action (ActionInterface< F > * impl) inline explicit
Definition at line 474 of file gmock-actions.h.
      : fun_(ActionAdapter{::std::shared_ptr<ActionInterface<F>>(impl)}) {}
Action() [4/4]
template<typename F > template<typename Func > testing::Action< F >::Action (const Action< Func > & action) inline explicit
Definition at line 481 of file gmock-actions.h.
: fun_(action.fun_) {}
Member Function Documentation
Init() [1/2]
template<typename F > template<typename G > void testing::Action< F >::Init (G && g, ::std::false_type) inline private
Definition at line 509 of file gmock-actions.h.
{
    fun_ = IgnoreArgs<typename ::std::decay<G>::type>{::std::forward<G>(g)};
  }
References testing::Action< F >::fun_.
Init() [2/2]
template<typename F > template<typename G > void testing::Action< F >::Init (G && g, ::std::true_type) inline private
Definition at line 504 of file gmock-actions.h.
{
    fun_ = ::std::forward<G>(g);
  }
References testing::Action< F >::fun_.
Referenced by testing::Action< F >::Action().
IsDoDefault()
template<typename F > bool testing::Action< F >::IsDoDefault () const inline
Definition at line 484 of file gmock-actions.h.
{ return fun_ == nullptr; }
References testing::Action< F >::fun_.
Referenced by testing::Action< F >::Perform().
Perform()
template<typename F > Result testing::Action< F >::Perform (ArgumentTuple args) const inline
Definition at line 492 of file gmock-actions.h.
{
    if (IsDoDefault()) {
      internal::IllegalDoDefault(__FILE__, __LINE__);
    }
    return internal::Apply(fun_, ::std::move(args));
  }
References testing::internal::Apply(), testing::Action< F >::fun_, testing::internal::IllegalDoDefault(), and testing::Action< F >::IsDoDefault().
Referenced by testing::internal::WithArgsAction< InnerAction, I >::operator Action< R(), testing::internal::DoAllAction< Actions >::operator Action< R(), and testing::internal::IgnoreResultAction< A >::Impl< F >::Perform().
Friends And Related Function Documentation
Action
template<typename F > template<typename G > friend class Action friend
Definition at line 501 of file gmock-actions.h.
Member Data Documentation
fun_
template<typename F > ::std::function<F> testing::Action< F >::fun_ private
Definition at line 524 of file gmock-actions.h.
Referenced by testing::Action< F >::Init(), testing::Action< F >::IsDoDefault(), and testing::Action< F >::Perform().
The documentation for this class was generated from the following file:
gmock-actions.h