MUSI6106: Interface Class Reference
Interface Class Reference abstract
#include <gmock_link_test.h>
Public Member Functions
virtual ~Interface ()
virtual void VoidFromString (char *str)=0
virtual char * StringFromString (char *str)=0
virtual int IntFromString (char *str)=0
virtual int & IntRefFromString (char *str)=0
virtual void VoidFromFunc (void(*func)(char *str))=0
virtual void VoidFromIntRef (int &n)=0
virtual void VoidFromFloat (float n)=0
virtual void VoidFromDouble (double n)=0
virtual void VoidFromVector (const std::vector< int > &v)=0
Detailed Description
Definition at line 196 of file gmock_link_test.h.
Constructor & Destructor Documentation
~Interface()
virtual Interface::~Interface () inline virtual
Definition at line 198 of file gmock_link_test.h.
{}
Member Function Documentation
IntFromString()
virtual int Interface::IntFromString (char * str) pure virtual
Referenced by TEST().
IntRefFromString()
virtual int & Interface::IntRefFromString (char * str) pure virtual
Referenced by TEST().
StringFromString()
virtual char * Interface::StringFromString (char * str) pure virtual
Referenced by TEST().
VoidFromDouble()
virtual void Interface::VoidFromDouble (double n) pure virtual
VoidFromFloat()
virtual void Interface::VoidFromFloat (float n) pure virtual
VoidFromFunc()
virtual void Interface::VoidFromFunc (void(*)(char *str) func) pure virtual
Referenced by TEST().
VoidFromIntRef()
virtual void Interface::VoidFromIntRef (int & n) pure virtual
VoidFromString()
virtual void Interface::VoidFromString (char * str) pure virtual
Referenced by TEST().
VoidFromVector()
virtual void Interface::VoidFromVector (const std::vector< int > & v) pure virtual
The documentation for this class was generated from the following file:
gmock_link_test.h