MUSI6106: InvokeHelper Class Reference
InvokeHelper Class Reference
#include <gmock_link_test.h>
Public Member Functions
void VoidFromVoid ()
void VoidFromString (char *)
Static Public Member Functions
static void StaticVoidFromVoid ()
static void StaticVoidFromString (char *)
static int StaticIntFromString (char *)
static bool StaticBoolFromString (const char *)
Detailed Description
Definition at line 228 of file gmock_link_test.h.
Member Function Documentation
StaticBoolFromString()
static bool InvokeHelper::StaticBoolFromString (const char *) inline static
Definition at line 235 of file gmock_link_test.h.
{ return true; }
Referenced by TEST().
StaticIntFromString()
static int InvokeHelper::StaticIntFromString (char *) inline static
Definition at line 234 of file gmock_link_test.h.
{ return 1; }
Referenced by TEST().
StaticVoidFromString()
static void InvokeHelper::StaticVoidFromString (char *) inline static
Definition at line 232 of file gmock_link_test.h.
{}
Referenced by TEST().
StaticVoidFromVoid()
static void InvokeHelper::StaticVoidFromVoid () inline static
Definition at line 230 of file gmock_link_test.h.
{}
Referenced by TEST().
VoidFromString()
void InvokeHelper::VoidFromString (char *) inline
Definition at line 233 of file gmock_link_test.h.
{}
Referenced by TEST().
VoidFromVoid()
void InvokeHelper::VoidFromVoid () inline
Definition at line 231 of file gmock_link_test.h.
{}
Referenced by TEST().
The documentation for this class was generated from the following file:
gmock_link_test.h