MUSI6106: testing::internal::FormatForComparison< ToPrint, OtherOperand > Class Template Reference
testing::internal::FormatForComparison< ToPrint, OtherOperand > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
::std::string Format (const ToPrint &value)
Detailed Description
template<typename ToPrint, typename OtherOperand>
class testing::internal::FormatForComparison< ToPrint, OtherOperand >
Definition at line 329 of file gtest-printers.h.
Member Function Documentation
Format()
template<typename ToPrint , typename OtherOperand > ::std::string testing::internal::FormatForComparison< ToPrint, OtherOperand >::Format (const ToPrint & value) inline static
Definition at line 331 of file gtest-printers.h.
{
    return ::testing::PrintToString(value);
  }
References testing::PrintToString().
Referenced by testing::internal::FormatForComparison< ToPrint[N], OtherOperand >::Format(), and testing::internal::FormatForComparisonFailureMessage().
The documentation for this class was generated from the following file:
gtest-printers.h