MUSI6106: testing::TestInfo Class Reference
testing::TestInfo Class Reference
#include <gtest.h>
Public Member Functions
~TestInfo ()
const char * test_suite_name () const
const char * test_case_name () const
const char * name () const
const char * type_param () const
const char * value_param () const
const char * file () const
int line () const
bool is_in_another_shard () const
bool should_run () const
bool is_reportable () const
const TestResult * result () const
Private Member Functions
TestInfo (const std::string &test_suite_name, const std::string &name, const char *a_type_param, const char *a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase *factory)
int increment_death_test_count ()
void Run ()
void Skip ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo)
Static Private Member Functions
static void ClearTestResult (TestInfo *test_info)
Private Attributes
const std::string test_suite_name_
const std::string name_
const std::unique_ptr< const ::std::string > type_param_
const std::unique_ptr< const ::std::string > value_param_
internal::CodeLocation location_
const internal::TypeId fixture_class_id_
bool should_run_
bool is_disabled_
bool matches_filter_
bool is_in_another_shard_
internal::TestFactoryBase *const factory_
TestResult result_
Friends
class Test
class TestSuite
class internal::UnitTestImpl
class internal::StreamingListenerTest
TestInfo * internal::MakeAndRegisterTestInfo (const char *test_suite_name, const char *name, const char *type_param, const char *value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc, internal::TestFactoryBase *factory)
Detailed Description
Definition at line 707 of file gtest.h.
Constructor & Destructor Documentation
~TestInfo()
testing::TestInfo::~TestInfo ()
TestInfo()
testing::TestInfo::TestInfo (const std::string & test_suite_name, const std::string & name, const char * a_type_param, const char * a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase * factory) private
Member Function Documentation
ClearTestResult()
static void testing::TestInfo::ClearTestResult (TestInfo * test_info) inline static private
Definition at line 812 of file gtest.h.
{
    test_info->result_.Clear();
  }
References testing::TestResult::Clear(), and result_.
file()
const char * testing::TestInfo::file () const inline
Definition at line 739 of file gtest.h.
{ return location_.file.c_str(); }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::TestInfo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo) private
increment_death_test_count()
int testing::TestInfo::increment_death_test_count () inline private
Definition at line 801 of file gtest.h.
{
    return result_.increment_death_test_count();
  }
is_in_another_shard()
bool testing::TestInfo::is_in_another_shard () const inline
Definition at line 745 of file gtest.h.
{ return is_in_another_shard_; }
is_reportable()
bool testing::TestInfo::is_reportable () const inline
Definition at line 766 of file gtest.h.
{
    // The XML report includes tests matching the filter, excluding those
    // run in other shards.
    return matches_filter_ && !is_in_another_shard_;
  }
Referenced by testing::TestSuite::TestReportable(), and testing::TestSuite::TestReportableDisabled().
line()
int testing::TestInfo::line () const inline
Definition at line 742 of file gtest.h.
{ return location_.line; }
name()
const char * testing::TestInfo::name () const inline
Definition at line 722 of file gtest.h.
{ return name_.c_str(); }
result()
const TestResult * testing::TestInfo::result () const inline
Definition at line 773 of file gtest.h.
{ return &result_; }
Referenced by testing::TestSuite::TestFailed(), testing::TestSuite::TestPassed(), and testing::TestSuite::TestSkipped().
Run()
void testing::TestInfo::Run () private
should_run()
bool testing::TestInfo::should_run () const inline
Definition at line 763 of file gtest.h.
{ return should_run_; }
Referenced by testing::TestSuite::ShouldRunTest(), testing::TestSuite::TestFailed(), testing::TestSuite::TestPassed(), and testing::TestSuite::TestSkipped().
Skip()
void testing::TestInfo::Skip () private
test_case_name()
const char * testing::TestInfo::test_case_name () const inline
Definition at line 718 of file gtest.h.
{ return test_suite_name(); }
test_suite_name()
const char * testing::TestInfo::test_suite_name () const inline
Definition at line 714 of file gtest.h.
{ return test_suite_name_.c_str(); }
Referenced by testing::internal::UnitTestImpl::AddTestInfo().
type_param()
const char * testing::TestInfo::type_param () const inline
Definition at line 726 of file gtest.h.
{
    if (type_param_.get() != nullptr) return type_param_->c_str();
    return nullptr;
  }
Referenced by testing::internal::UnitTestImpl::AddTestInfo().
value_param()
const char * testing::TestInfo::value_param () const inline
Definition at line 733 of file gtest.h.
{
    if (value_param_.get() != nullptr) return value_param_->c_str();
    return nullptr;
  }
Friends And Related Function Documentation
internal::MakeAndRegisterTestInfo
TestInfo * internal::MakeAndRegisterTestInfo (const char * test_suite_name, const char * name, const char * type_param, const char * value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc, internal::TestFactoryBase * factory) friend
internal::StreamingListenerTest
friend class internal::StreamingListenerTest friend
Definition at line 782 of file gtest.h.
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 781 of file gtest.h.
Test
friend class Test friend
Definition at line 779 of file gtest.h.
TestSuite
friend class TestSuite friend
Definition at line 780 of file gtest.h.
Member Data Documentation
factory_
internal::TestFactoryBase* const testing::TestInfo::factory_ private
Definition at line 832 of file gtest.h.
fixture_class_id_
const internal::TypeId testing::TestInfo::fixture_class_id_ private
Definition at line 826 of file gtest.h.
is_disabled_
bool testing::TestInfo::is_disabled_ private
Definition at line 828 of file gtest.h.
Referenced by testing::TestSuite::TestDisabled(), and testing::TestSuite::TestReportableDisabled().
is_in_another_shard_
bool testing::TestInfo::is_in_another_shard_ private
Definition at line 831 of file gtest.h.
location_
internal::CodeLocation testing::TestInfo::location_ private
Definition at line 825 of file gtest.h.
matches_filter_
bool testing::TestInfo::matches_filter_ private
Definition at line 829 of file gtest.h.
name_
const std::string testing::TestInfo::name_ private
Definition at line 818 of file gtest.h.
result_
TestResult testing::TestInfo::result_ private
Definition at line 837 of file gtest.h.
Referenced by ClearTestResult().
should_run_
bool testing::TestInfo::should_run_ private
Definition at line 827 of file gtest.h.
test_suite_name_
const std::string testing::TestInfo::test_suite_name_ private
Definition at line 817 of file gtest.h.
type_param_
const std::unique_ptr<const ::std::string> testing::TestInfo::type_param_ private
Definition at line 821 of file gtest.h.
value_param_
const std::unique_ptr<const ::std::string> testing::TestInfo::value_param_ private
Definition at line 824 of file gtest.h.
The documentation for this class was generated from the following file:
gtest.h