MUSI6106: testing::TestResult Class Reference
testing::TestResult Class Reference
#include <gtest.h>
Public Member Functions
TestResult ()
~TestResult ()
int total_part_count () const
int test_property_count () const
bool Passed () const
bool Skipped () const
bool Failed () const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
TimeInMillis elapsed_time () const
TimeInMillis start_timestamp () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
Private Member Functions
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
void set_start_timestamp (TimeInMillis start)
void set_elapsed_time (TimeInMillis elapsed)
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void AddTestPartResult (const TestPartResult &test_part_result)
int death_test_count () const
int increment_death_test_count ()
void ClearTestPartResults ()
void Clear ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
Static Private Member Functions
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
Private Attributes
internal::Mutex test_properties_mutex_
std::vector< TestPartResult > test_part_results_
std::vector< TestProperty > test_properties_
int death_test_count_
TimeInMillis start_timestamp_
TimeInMillis elapsed_time_
Friends
class TestInfo
class TestSuite
class UnitTest
class internal::DefaultGlobalTestPartResultReporter
class internal::ExecDeathTest
class internal::TestResultAccessor
class internal::UnitTestImpl
class internal::WindowsDeathTest
class internal::FuchsiaDeathTest
Detailed Description
Definition at line 574 of file gtest.h.
Constructor & Destructor Documentation
TestResult()
testing::TestResult::TestResult ()
~TestResult()
testing::TestResult::~TestResult ()
Member Function Documentation
AddTestPartResult()
void testing::TestResult::AddTestPartResult (const TestPartResult & test_part_result) private
Clear()
void testing::TestResult::Clear () private
Referenced by testing::TestInfo::ClearTestResult().
ClearTestPartResults()
void testing::TestResult::ClearTestPartResults () private
Referenced by testing::internal::TestResultAccessor::ClearTestPartResults().
death_test_count()
int testing::TestResult::death_test_count () const inline private
Definition at line 666 of file gtest.h.
{ return death_test_count_; }
elapsed_time()
TimeInMillis testing::TestResult::elapsed_time () const inline
Definition at line 605 of file gtest.h.
{ return elapsed_time_; }
Failed()
bool testing::TestResult::Failed () const
Referenced by testing::TestSuite::TestFailed().
GetTestPartResult()
const TestPartResult & testing::TestResult::GetTestPartResult (int i) const
GetTestProperty()
const TestProperty & testing::TestResult::GetTestProperty (int i) const
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::TestResult::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) private
HasFatalFailure()
bool testing::TestResult::HasFatalFailure () const
HasNonfatalFailure()
bool testing::TestResult::HasNonfatalFailure () const
increment_death_test_count()
int testing::TestResult::increment_death_test_count () inline private
Definition at line 669 of file gtest.h.
{ return ++death_test_count_; }
Passed()
bool testing::TestResult::Passed () const inline
Definition at line 590 of file gtest.h.
{ return !Skipped() && !Failed(); }
Referenced by testing::TestSuite::TestPassed().
RecordProperty()
void testing::TestResult::RecordProperty (const std::string & xml_element, const TestProperty & test_property) private
Referenced by testing::internal::TestResultAccessor::RecordProperty().
set_elapsed_time()
void testing::TestResult::set_elapsed_time (TimeInMillis elapsed) inline private
Definition at line 645 of file gtest.h.
{ elapsed_time_ = elapsed; }
set_start_timestamp()
void testing::TestResult::set_start_timestamp (TimeInMillis start) inline private
Definition at line 642 of file gtest.h.
{ start_timestamp_ = start; }
Skipped()
bool testing::TestResult::Skipped () const
Referenced by testing::TestSuite::TestSkipped().
start_timestamp()
TimeInMillis testing::TestResult::start_timestamp () const inline
Definition at line 609 of file gtest.h.
{ return start_timestamp_; }
test_part_results()
const std::vector< TestPartResult > & testing::TestResult::test_part_results () const inline private
Definition at line 632 of file gtest.h.
{
    return test_part_results_;
  }
Referenced by testing::internal::TestResultAccessor::test_part_results().
test_properties()
const std::vector< TestProperty > & testing::TestResult::test_properties () const inline private
Definition at line 637 of file gtest.h.
{
    return test_properties_;
  }
test_property_count()
int testing::TestResult::test_property_count () const
total_part_count()
int testing::TestResult::total_part_count () const
ValidateTestProperty()
static bool testing::TestResult::ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) static private
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter
friend class internal::DefaultGlobalTestPartResultReporter friend
Definition at line 624 of file gtest.h.
internal::ExecDeathTest
friend class internal::ExecDeathTest friend
Definition at line 625 of file gtest.h.
internal::FuchsiaDeathTest
friend class internal::FuchsiaDeathTest friend
Definition at line 629 of file gtest.h.
internal::TestResultAccessor
friend class internal::TestResultAccessor friend
Definition at line 626 of file gtest.h.
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 627 of file gtest.h.
internal::WindowsDeathTest
friend class internal::WindowsDeathTest friend
Definition at line 628 of file gtest.h.
TestInfo
friend class TestInfo friend
Definition at line 621 of file gtest.h.
TestSuite
friend class TestSuite friend
Definition at line 622 of file gtest.h.
UnitTest
friend class UnitTest friend
Definition at line 623 of file gtest.h.
Member Data Documentation
death_test_count_
int testing::TestResult::death_test_count_ private
Definition at line 686 of file gtest.h.
elapsed_time_
TimeInMillis testing::TestResult::elapsed_time_ private
Definition at line 690 of file gtest.h.
start_timestamp_
TimeInMillis testing::TestResult::start_timestamp_ private
Definition at line 688 of file gtest.h.
test_part_results_
std::vector<TestPartResult> testing::TestResult::test_part_results_ private
Definition at line 682 of file gtest.h.
test_properties_
std::vector<TestProperty> testing::TestResult::test_properties_ private
Definition at line 684 of file gtest.h.
test_properties_mutex_
internal::Mutex testing::TestResult::test_properties_mutex_ private
Definition at line 679 of file gtest.h.
The documentation for this class was generated from the following file:
gtest.h