MUSI6106: testing::Test Class Reference
testing::Test Class Reference abstract
#include <gtest.h>
Classes
struct Setup_should_be_spelled_SetUp
Public Member Functions
virtual ~Test ()
Static Public Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static void TearDownTestCase ()
static void SetUpTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool IsSkipped ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions
Test ()
virtual void SetUp ()
virtual void TearDown ()
Private Member Functions
virtual void TestBody ()=0
void Run ()
void DeleteSelf_ ()
virtual Setup_should_be_spelled_SetUp * Setup ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
Static Private Member Functions
static bool HasSameFixtureClass ()
Private Attributes
const std::unique_ptr< GTEST_FLAG_SAVER_ > gtest_flag_saver_
Friends
class TestInfo
Detailed Description
Definition at line 417 of file gtest.h.
Constructor & Destructor Documentation
~Test()
virtual testing::Test::~Test () virtual
Test()
testing::Test::Test () protected
Member Function Documentation
DeleteSelf_()
void testing::Test::DeleteSelf_ () inline private
Definition at line 504 of file gtest.h.
{ delete this; }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::Test::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) private
HasFailure()
static bool testing::Test::HasFailure () inline static
Definition at line 458 of file gtest.h.
{ return HasFatalFailure() || HasNonfatalFailure(); }
HasFatalFailure()
static bool testing::Test::HasFatalFailure () static
HasNonfatalFailure()
static bool testing::Test::HasNonfatalFailure () static
HasSameFixtureClass()
static bool testing::Test::HasSameFixtureClass () static private
IsSkipped()
static bool testing::Test::IsSkipped () static
RecordProperty() [1/2]
static void testing::Test::RecordProperty (const std::string & key, const std::string & value) static
RecordProperty() [2/2]
static void testing::Test::RecordProperty (const std::string & key, int value) static
Run()
void testing::Test::Run () private
SetUp()
virtual void testing::Test::SetUp () protected virtual
Setup()
virtual Setup_should_be_spelled_SetUp * testing::Test::Setup () inline private virtual
Definition at line 525 of file gtest.h.
{ return nullptr; }
SetUpTestCase()
static void testing::Test::SetUpTestCase () inline static
Definition at line 444 of file gtest.h.
{}
Referenced by testing::internal::SuiteApiResolver< T >::GetSetUpCaseOrSuite().
SetUpTestSuite()
static void testing::Test::SetUpTestSuite () inline static
Definition at line 430 of file gtest.h.
{}
Referenced by testing::internal::SuiteApiResolver< T >::GetSetUpCaseOrSuite().
TearDown()
virtual void testing::Test::TearDown () protected virtual
TearDownTestCase()
static void testing::Test::TearDownTestCase () inline static
Definition at line 443 of file gtest.h.
{}
Referenced by testing::internal::SuiteApiResolver< T >::GetTearDownCaseOrSuite().
TearDownTestSuite()
static void testing::Test::TearDownTestSuite () inline static
Definition at line 438 of file gtest.h.
{}
Referenced by testing::internal::SuiteApiResolver< T >::GetTearDownCaseOrSuite().
TestBody()
virtual void testing::Test::TestBody () private pure virtual
Friends And Related Function Documentation
TestInfo
friend class TestInfo friend
Definition at line 419 of file gtest.h.
Member Data Documentation
gtest_flag_saver_
const std::unique_ptr<GTEST_FLAG_SAVER_> testing::Test::gtest_flag_saver_ private
Definition at line 506 of file gtest.h.
The documentation for this class was generated from the following file:
gtest.h