MUSI6106: testing::internal::NativeArray< Element > Class Template Reference
testing::internal::NativeArray< Element > Class Template Reference
#include <gtest-internal.h>
Public Types
typedef Element value_type
typedef Element * iterator
typedef const Element * const_iterator
Public Member Functions
NativeArray (const Element *array, size_t count, RelationToSourceReference)
NativeArray (const Element *array, size_t count, RelationToSourceCopy)
NativeArray (const NativeArray &rhs)
~NativeArray ()
size_t size () const
const_iterator begin () const
const_iterator end () const
bool operator== (const NativeArray &rhs) const
Private Member Functions
void InitCopy (const Element *array, size_t a_size)
void InitRef (const Element *array, size_t a_size)
Private Attributes
const Element * array_
size_t size_
void(NativeArray::* clone_)(const Element *, size_t)
Detailed Description
template<typename Element>
class testing::internal::NativeArray< Element >
Definition at line 1092 of file gtest-internal.h.
Member Typedef Documentation
const_iterator
template<typename Element > typedef const Element* testing::internal::NativeArray< Element >::const_iterator
Definition at line 1097 of file gtest-internal.h.
iterator
template<typename Element > typedef Element* testing::internal::NativeArray< Element >::iterator
Definition at line 1096 of file gtest-internal.h.
value_type
template<typename Element > typedef Element testing::internal::NativeArray< Element >::value_type
Definition at line 1095 of file gtest-internal.h.
Constructor & Destructor Documentation
NativeArray() [1/3]
template<typename Element > testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceReference) inline
Definition at line 1100 of file gtest-internal.h.
{
    InitRef(array, count);
  }
References testing::internal::NativeArray< Element >::InitRef().
NativeArray() [2/3]
template<typename Element > testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceCopy) inline
Definition at line 1105 of file gtest-internal.h.
{
    InitCopy(array, count);
  }
References testing::internal::NativeArray< Element >::InitCopy().
NativeArray() [3/3]
template<typename Element > testing::internal::NativeArray< Element >::NativeArray (const NativeArray< Element > & rhs) inline
Definition at line 1110 of file gtest-internal.h.
{
    (this->*rhs.clone_)(rhs.array_, rhs.size_);
  }
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, and testing::internal::NativeArray< Element >::size_.
~NativeArray()
template<typename Element > testing::internal::NativeArray< Element >::~NativeArray () inline
Definition at line 1114 of file gtest-internal.h.
                 {
    if (clone_ != &NativeArray::InitRef)
      delete[] array_;
  }
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, and testing::internal::NativeArray< Element >::InitRef().
Member Function Documentation
begin()
template<typename Element > const_iterator testing::internal::NativeArray< Element >::begin () const inline
Definition at line 1121 of file gtest-internal.h.
{ return array_; }
References testing::internal::NativeArray< Element >::array_.
Referenced by testing::internal::NativeArray< Element >::operator==().
end()
template<typename Element > const_iterator testing::internal::NativeArray< Element >::end () const inline
Definition at line 1122 of file gtest-internal.h.
{ return array_ + size_; }
References testing::internal::NativeArray< Element >::array_, and testing::internal::NativeArray< Element >::size_.
InitCopy()
template<typename Element > void testing::internal::NativeArray< Element >::InitCopy (const Element * array, size_t a_size) inline private
Definition at line 1134 of file gtest-internal.h.
{
    Element* const copy = new Element[a_size];
    CopyArray(array, a_size, copy);
    array_ = copy;
    size_ = a_size;
    clone_ = &NativeArray::InitCopy;
  }
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, testing::internal::CopyArray(), testing::internal::NativeArray< Element >::InitCopy(), and testing::internal::NativeArray< Element >::size_.
Referenced by testing::internal::NativeArray< Element >::InitCopy(), and testing::internal::NativeArray< Element >::NativeArray().
InitRef()
template<typename Element > void testing::internal::NativeArray< Element >::InitRef (const Element * array, size_t a_size) inline private
Definition at line 1143 of file gtest-internal.h.
{
    array_ = array;
    size_ = a_size;
    clone_ = &NativeArray::InitRef;
  }
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, testing::internal::NativeArray< Element >::InitRef(), and testing::internal::NativeArray< Element >::size_.
Referenced by testing::internal::NativeArray< Element >::InitRef(), testing::internal::NativeArray< Element >::NativeArray(), and testing::internal::NativeArray< Element >::~NativeArray().
operator==()
template<typename Element > bool testing::internal::NativeArray< Element >::operator== (const NativeArray< Element > & rhs) const inline
Definition at line 1123 of file gtest-internal.h.
{
    return size() == rhs.size() &&
        ArrayEq(begin(), size(), rhs.begin());
  }
References testing::internal::ArrayEq(), testing::internal::NativeArray< Element >::begin(), and testing::internal::NativeArray< Element >::size().
size()
template<typename Element > size_t testing::internal::NativeArray< Element >::size () const inline
Definition at line 1120 of file gtest-internal.h.
{ return size_; }
References testing::internal::NativeArray< Element >::size_.
Referenced by testing::internal::NativeArray< Element >::operator==().
Member Data Documentation
array_
template<typename Element > const Element* testing::internal::NativeArray< Element >::array_ private
Definition at line 1149 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::begin(), testing::internal::NativeArray< Element >::end(), testing::internal::NativeArray< Element >::InitCopy(), testing::internal::NativeArray< Element >::InitRef(), testing::internal::NativeArray< Element >::NativeArray(), and testing::internal::NativeArray< Element >::~NativeArray().
clone_
template<typename Element > void(NativeArray::* testing::internal::NativeArray< Element >::clone_) (const Element *, size_t) private
Definition at line 1151 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::InitCopy(), testing::internal::NativeArray< Element >::InitRef(), testing::internal::NativeArray< Element >::NativeArray(), and testing::internal::NativeArray< Element >::~NativeArray().
size_
template<typename Element > size_t testing::internal::NativeArray< Element >::size_ private
Definition at line 1150 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::end(), testing::internal::NativeArray< Element >::InitCopy(), testing::internal::NativeArray< Element >::InitRef(), testing::internal::NativeArray< Element >::NativeArray(), and testing::internal::NativeArray< Element >::size().
The documentation for this class was generated from the following file:
gtest-internal.h