MUSI6106: testing::internal::FloatingPoint< RawType > Class Template Reference
testing::internal::FloatingPoint< RawType > Class Template Reference
#include <gtest-internal.h>
Classes
union FloatingPointUnion
Public Types
typedef TypeWithSize< sizeof(RawType)>::UInt Bits
Public Member Functions
FloatingPoint (const RawType &x)
const Bits & bits () const
Bits exponent_bits () const
Bits fraction_bits () const
Bits sign_bit () const
bool is_nan () const
bool AlmostEquals (const FloatingPoint &rhs) const
float Max ()
double Max ()
Static Public Member Functions
static RawType ReinterpretBits (const Bits bits)
static RawType Infinity ()
static RawType Max ()
Static Public Attributes
static const size_t kBitCount = 8*sizeof(RawType)
static const size_t kFractionBitCount
static const size_t kExponentBitCount = kBitCount - 1 - kFractionBitCount
static const Bits kSignBitMask = static_cast<Bits>(1) << (kBitCount - 1)
static const Bits kFractionBitMask
static const Bits kExponentBitMask = ~(kSignBitMask | kFractionBitMask)
static const uint32_t kMaxUlps = 4
Static Private Member Functions
static Bits SignAndMagnitudeToBiased (const Bits &sam)
static Bits DistanceBetweenSignAndMagnitudeNumbers (const Bits &sam1, const Bits &sam2)
Private Attributes
FloatingPointUnion u_
Detailed Description
template<typename RawType>
class testing::internal::FloatingPoint< RawType >
Definition at line 248 of file gtest-internal.h.
Member Typedef Documentation
Bits
template<typename RawType > typedef TypeWithSize<sizeof(RawType)>::UInt testing::internal::FloatingPoint< RawType >::Bits
Definition at line 252 of file gtest-internal.h.
Constructor & Destructor Documentation
FloatingPoint()
template<typename RawType > testing::internal::FloatingPoint< RawType >::FloatingPoint (const RawType & x) inline explicit
Definition at line 296 of file gtest-internal.h.
{ u_.value_ = x; }
References testing::internal::FloatingPoint< RawType >::u_, and testing::internal::FloatingPoint< RawType >::FloatingPointUnion::value_.
Member Function Documentation
AlmostEquals()
template<typename RawType > bool testing::internal::FloatingPoint< RawType >::AlmostEquals (const FloatingPoint< RawType > & rhs) const inline
Definition at line 344 of file gtest-internal.h.
{
    // The IEEE standard says that any comparison operation involving
    // a NAN must return false.
    if (is_nan() || rhs.is_nan()) return false;
    return DistanceBetweenSignAndMagnitudeNumbers(u_.bits_, rhs.u_.bits_)
        <= kMaxUlps;
  }
References testing::internal::FloatingPoint< RawType >::FloatingPointUnion::bits_, testing::internal::FloatingPoint< RawType >::DistanceBetweenSignAndMagnitudeNumbers(), testing::internal::FloatingPoint< RawType >::is_nan(), testing::internal::FloatingPoint< RawType >::kMaxUlps, and testing::internal::FloatingPoint< RawType >::u_.
bits()
template<typename RawType > const Bits & testing::internal::FloatingPoint< RawType >::bits () const inline
Definition at line 320 of file gtest-internal.h.
{ return u_.bits_; }
References testing::internal::FloatingPoint< RawType >::FloatingPointUnion::bits_, and testing::internal::FloatingPoint< RawType >::u_.
Referenced by testing::internal::FloatingPoint< RawType >::ReinterpretBits().
DistanceBetweenSignAndMagnitudeNumbers()
template<typename RawType > static Bits testing::internal::FloatingPoint< RawType >::DistanceBetweenSignAndMagnitudeNumbers (const Bits & sam1, const Bits & sam2) inline static private
Definition at line 387 of file gtest-internal.h.
{
    const Bits biased1 = SignAndMagnitudeToBiased(sam1);
    const Bits biased2 = SignAndMagnitudeToBiased(sam2);
    return (biased1 >= biased2) ? (biased1 - biased2) : (biased2 - biased1);
  }
References testing::internal::FloatingPoint< RawType >::SignAndMagnitudeToBiased().
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals().
exponent_bits()
template<typename RawType > Bits testing::internal::FloatingPoint< RawType >::exponent_bits () const inline
Definition at line 323 of file gtest-internal.h.
{ return kExponentBitMask & u_.bits_; }
References testing::internal::FloatingPoint< RawType >::FloatingPointUnion::bits_, testing::internal::FloatingPoint< RawType >::kExponentBitMask, and testing::internal::FloatingPoint< RawType >::u_.
Referenced by testing::internal::FloatingPoint< RawType >::is_nan().
fraction_bits()
template<typename RawType > Bits testing::internal::FloatingPoint< RawType >::fraction_bits () const inline
Definition at line 326 of file gtest-internal.h.
{ return kFractionBitMask & u_.bits_; }
References testing::internal::FloatingPoint< RawType >::FloatingPointUnion::bits_, testing::internal::FloatingPoint< RawType >::kFractionBitMask, and testing::internal::FloatingPoint< RawType >::u_.
Referenced by testing::internal::FloatingPoint< RawType >::is_nan().
Infinity()
template<typename RawType > static RawType testing::internal::FloatingPoint< RawType >::Infinity () inline static
Definition at line 310 of file gtest-internal.h.
{
    return ReinterpretBits(kExponentBitMask);
  }
References testing::internal::FloatingPoint< RawType >::kExponentBitMask, and testing::internal::FloatingPoint< RawType >::ReinterpretBits().
is_nan()
template<typename RawType > bool testing::internal::FloatingPoint< RawType >::is_nan () const inline
Definition at line 332 of file gtest-internal.h.
                      {
    // It's a NAN if the exponent bits are all ones and the fraction
    // bits are not entirely zeros.
    return (exponent_bits() == kExponentBitMask) && (fraction_bits() != 0);
  }
References testing::internal::FloatingPoint< RawType >::exponent_bits(), testing::internal::FloatingPoint< RawType >::fraction_bits(), and testing::internal::FloatingPoint< RawType >::kExponentBitMask.
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals().
Max() [1/3]
template<typename RawType > static RawType testing::internal::FloatingPoint< RawType >::Max () static
Max() [2/3]
float testing::internal::FloatingPoint< float >::Max () inline
Definition at line 400 of file gtest-internal.h.
{ return FLT_MAX; }
Max() [3/3]
double testing::internal::FloatingPoint< double >::Max () inline
Definition at line 402 of file gtest-internal.h.
{ return DBL_MAX; }
ReinterpretBits()
template<typename RawType > static RawType testing::internal::FloatingPoint< RawType >::ReinterpretBits (const Bits bits) inline static
Definition at line 303 of file gtest-internal.h.
{
    FloatingPoint fp(0);
    fp.u_.bits_ = bits;
    return fp.u_.value_;
  }
References testing::internal::FloatingPoint< RawType >::bits(), testing::internal::FloatingPoint< RawType >::FloatingPointUnion::bits_, testing::internal::FloatingPoint< RawType >::u_, and testing::internal::FloatingPoint< RawType >::FloatingPointUnion::value_.
Referenced by testing::internal::FloatingPoint< RawType >::Infinity().
sign_bit()
template<typename RawType > Bits testing::internal::FloatingPoint< RawType >::sign_bit () const inline
Definition at line 329 of file gtest-internal.h.
{ return kSignBitMask & u_.bits_; }
References testing::internal::FloatingPoint< RawType >::FloatingPointUnion::bits_, testing::internal::FloatingPoint< RawType >::kSignBitMask, and testing::internal::FloatingPoint< RawType >::u_.
SignAndMagnitudeToBiased()
template<typename RawType > static Bits testing::internal::FloatingPoint< RawType >::SignAndMagnitudeToBiased (const Bits & sam) inline static private
Definition at line 375 of file gtest-internal.h.
{
    if (kSignBitMask & sam) {
      // sam represents a negative number.
      return ~sam + 1;
    } else {
      // sam represents a positive number.
      return kSignBitMask | sam;
    }
  }
References testing::internal::FloatingPoint< RawType >::kSignBitMask.
Referenced by testing::internal::FloatingPoint< RawType >::DistanceBetweenSignAndMagnitudeNumbers().
Member Data Documentation
kBitCount
template<typename RawType > const size_t testing::internal::FloatingPoint< RawType >::kBitCount = 8*sizeof(RawType) static
Definition at line 257 of file gtest-internal.h.
kExponentBitCount
template<typename RawType > const size_t testing::internal::FloatingPoint< RawType >::kExponentBitCount = kBitCount - 1 - kFractionBitCount static
Definition at line 264 of file gtest-internal.h.
kExponentBitMask
template<typename RawType > const Bits testing::internal::FloatingPoint< RawType >::kExponentBitMask = ~(kSignBitMask | kFractionBitMask) static
Definition at line 274 of file gtest-internal.h.
Referenced by testing::internal::FloatingPoint< RawType >::exponent_bits(), testing::internal::FloatingPoint< RawType >::Infinity(), and testing::internal::FloatingPoint< RawType >::is_nan().
kFractionBitCount
template<typename RawType > const size_t testing::internal::FloatingPoint< RawType >::kFractionBitCount static
Initial value:
=
    std::numeric_limits<RawType>::digits - 1
Definition at line 260 of file gtest-internal.h.
kFractionBitMask
template<typename RawType > const Bits testing::internal::FloatingPoint< RawType >::kFractionBitMask static
Initial value:
=
    ~static_cast<Bits>(0) >> (kExponentBitCount + 1)
Definition at line 270 of file gtest-internal.h.
Referenced by testing::internal::FloatingPoint< RawType >::fraction_bits().
kMaxUlps
template<typename RawType > const uint32_t testing::internal::FloatingPoint< RawType >::kMaxUlps = 4 static
Definition at line 288 of file gtest-internal.h.
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals().
kSignBitMask
template<typename RawType > const Bits testing::internal::FloatingPoint< RawType >::kSignBitMask = static_cast<Bits>(1) << (kBitCount - 1) static
Definition at line 267 of file gtest-internal.h.
Referenced by testing::internal::FloatingPoint< RawType >::sign_bit(), and testing::internal::FloatingPoint< RawType >::SignAndMagnitudeToBiased().
u_
template<typename RawType > FloatingPointUnion testing::internal::FloatingPoint< RawType >::u_ private
Definition at line 394 of file gtest-internal.h.
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals(), testing::internal::FloatingPoint< RawType >::bits(), testing::internal::FloatingPoint< RawType >::exponent_bits(), testing::internal::FloatingPoint< RawType >::FloatingPoint(), testing::internal::FloatingPoint< RawType >::fraction_bits(), testing::internal::FloatingPoint< RawType >::ReinterpretBits(), and testing::internal::FloatingPoint< RawType >::sign_bit().
The documentation for this class was generated from the following file:
gtest-internal.h