MUSI6106: testing::internal::ParamIteratorInterface< T > Class Template Reference
testing::internal::ParamIteratorInterface< T > Class Template Reference abstract
#include <gtest-param-util.h>
Public Member Functions
virtual ~ParamIteratorInterface ()
virtual const ParamGeneratorInterface< T > * BaseGenerator () const =0
virtual void Advance ()=0
virtual ParamIteratorInterface * Clone () const =0
virtual const T * Current () const =0
virtual bool Equals (const ParamIteratorInterface &other) const =0
Detailed Description
template<typename T>
class testing::internal::ParamIteratorInterface< T >
Definition at line 91 of file gtest-param-util.h.
Constructor & Destructor Documentation
~ParamIteratorInterface()
template<typename T > virtual testing::internal::ParamIteratorInterface< T >::~ParamIteratorInterface () inline virtual
Definition at line 93 of file gtest-param-util.h.
{}
Member Function Documentation
Advance()
template<typename T > virtual void testing::internal::ParamIteratorInterface< T >::Advance () pure virtual
Implemented in testing::internal::RangeGenerator< T, IncrementT >::Iterator, testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >.
BaseGenerator()
template<typename T > virtual const ParamGeneratorInterface< T > * testing::internal::ParamIteratorInterface< T >::BaseGenerator () const pure virtual
Implemented in testing::internal::RangeGenerator< T, IncrementT >::Iterator, testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >.
Referenced by testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >::Equals(), testing::internal::RangeGenerator< T, IncrementT >::Iterator::Equals(), and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Equals().
Clone()
template<typename T > virtual ParamIteratorInterface * testing::internal::ParamIteratorInterface< T >::Clone () const pure virtual
Implemented in testing::internal::RangeGenerator< T, IncrementT >::Iterator, testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >.
Current()
template<typename T > virtual const T * testing::internal::ParamIteratorInterface< T >::Current () const pure virtual
Implemented in testing::internal::RangeGenerator< T, IncrementT >::Iterator, testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >.
Equals()
template<typename T > virtual bool testing::internal::ParamIteratorInterface< T >::Equals (const ParamIteratorInterface< T > & other) const pure virtual
Implemented in testing::internal::RangeGenerator< T, IncrementT >::Iterator, and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator.
The documentation for this class was generated from the following file:
gtest-param-util.h