MUSI6106: testing::internal::RE Class Reference
testing::internal::RE Class Reference
#include <gtest-port.h>
Public Member Functions
RE (const RE &other)
RE (const ::std::string &regex)
RE (const char *regex)
~RE ()
const char * pattern () const
Static Public Member Functions
static bool FullMatch (const ::std::string &str, const RE &re)
static bool PartialMatch (const ::std::string &str, const RE &re)
static bool FullMatch (const char *str, const RE &re)
static bool PartialMatch (const char *str, const RE &re)
Private Member Functions
void Init (const char *regex)
Private Attributes
const char * pattern_
bool is_valid_
regex_t full_regex_
regex_t partial_regex_
Detailed Description
Definition at line 903 of file gtest-port.h.
Constructor & Destructor Documentation
RE() [1/3]
testing::internal::RE::RE (const RE & other) inline
Definition at line 907 of file gtest-port.h.
{ Init(other.pattern()); }
References pattern().
RE() [2/3]
testing::internal::RE::RE (const ::std::string & regex) inline
Definition at line 910 of file gtest-port.h.
{ Init(regex.c_str()); }  // NOLINT
RE() [3/3]
testing::internal::RE::RE (const char * regex) inline
Definition at line 912 of file gtest-port.h.
{ Init(regex); }  // NOLINT
~RE()
testing::internal::RE::~RE ()
Member Function Documentation
FullMatch() [1/2]
static bool testing::internal::RE::FullMatch (const ::std::string & str, const RE & re) inline static
Definition at line 922 of file gtest-port.h.
{
    return FullMatch(str.c_str(), re);
  }
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_().
FullMatch() [2/2]
static bool testing::internal::RE::FullMatch (const char * str, const RE & re) static
Init()
void testing::internal::RE::Init (const char * regex) private
PartialMatch() [1/2]
static bool testing::internal::RE::PartialMatch (const ::std::string & str, const RE & re) inline static
Definition at line 925 of file gtest-port.h.
{
    return PartialMatch(str.c_str(), re);
  }
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_().
PartialMatch() [2/2]
static bool testing::internal::RE::PartialMatch (const char * str, const RE & re) static
pattern()
const char * testing::internal::RE::pattern () const inline
Definition at line 916 of file gtest-port.h.
{ return pattern_; }
Referenced by RE().
Member Data Documentation
full_regex_
regex_t testing::internal::RE::full_regex_ private
Definition at line 939 of file gtest-port.h.
is_valid_
bool testing::internal::RE::is_valid_ private
Definition at line 935 of file gtest-port.h.
partial_regex_
regex_t testing::internal::RE::partial_regex_ private
Definition at line 940 of file gtest-port.h.
pattern_
const char* testing::internal::RE::pattern_ private
Definition at line 934 of file gtest-port.h.
The documentation for this class was generated from the following file:
gtest-port.h