MUSI6106: MyString Class Reference
MyString Class Reference
#include <sample2.h>
Public Member Functions
MyString ()
MyString (const char *a_c_string)
MyString (const MyString &string)
~MyString ()
const char * c_string () const
size_t Length () const
void Set (const char *c_string)
Static Public Member Functions
static const char * CloneCString (const char *a_c_string)
Private Member Functions
const MyString & operator= (const MyString &rhs)
Private Attributes
const char * c_string_
Detailed Description
Definition at line 39 of file sample2.h.
Constructor & Destructor Documentation
MyString() [1/3]
MyString::MyString () inline
Definition at line 53 of file sample2.h.
: c_string_(nullptr) {}
MyString() [2/3]
MyString::MyString (const char * a_c_string) inline explicit
Definition at line 56 of file sample2.h.
                                            : c_string_(nullptr) {
    Set(a_c_string);
  }
References Set().
MyString() [3/3]
MyString::MyString (const MyString & string) inline
Definition at line 61 of file sample2.h.
                                   : c_string_(nullptr) {
    Set(string.c_string_);
  }
References c_string_, and Set().
~MyString()
MyString::~MyString () inline
Definition at line 69 of file sample2.h.
{ delete[] c_string_; }
References c_string_.
Member Function Documentation
c_string()
const char * MyString::c_string () const inline
Definition at line 72 of file sample2.h.
{ return c_string_; }
References c_string_.
CloneCString()
static const char * MyString::CloneCString (const char * a_c_string) static
Length()
size_t MyString::Length () const inline
Definition at line 74 of file sample2.h.
{ return c_string_ == nullptr ? 0 : strlen(c_string_); }
References c_string_.
operator=()
const MyString & MyString::operator= (const MyString & rhs) private
Set()
void MyString::Set (const char * c_string)
Referenced by MyString().
Member Data Documentation
c_string_
const char* MyString::c_string_ private
Definition at line 41 of file sample2.h.
Referenced by c_string(), Length(), MyString(), and ~MyString().
The documentation for this class was generated from the following file:
sample2.h