MUSI6106: testing::internal::UnitTestImpl Class Reference
testing::internal::UnitTestImpl Class Reference
#include <gtest-internal-inl.h>
Public Types
enum ReactionToSharding { HONOR_SHARDING_PROTOCOL , IGNORE_SHARDING_PROTOCOL }
Public Member Functions
UnitTestImpl (UnitTest *parent)
virtual ~UnitTestImpl ()
TestPartResultReporterInterface * GetGlobalTestPartResultReporter ()
void SetGlobalTestPartResultReporter (TestPartResultReporterInterface *reporter)
TestPartResultReporterInterface * GetTestPartResultReporterForCurrentThread ()
void SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface *reporter)
int successful_test_suite_count () const
int failed_test_suite_count () const
int total_test_suite_count () const
int test_suite_to_run_count () const
int successful_test_count () const
int skipped_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestSuite * GetTestSuite (int i) const
const TestCase * GetTestCase (int i) const
TestSuite * GetMutableSuiteCase (int i)
TestEventListeners * listeners ()
TestResult * current_test_result ()
const TestResult * ad_hoc_test_result () const
void set_os_stack_trace_getter (OsStackTraceGetterInterface *getter)
OsStackTraceGetterInterface * os_stack_trace_getter ()
std::string CurrentOsStackTraceExceptTop (int skip_count) GTEST_NO_INLINE_
TestSuite * GetTestSuite (const char *test_suite_name, const char *type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
TestCase * GetTestCase (const char *test_case_name, const char *type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
void AddTestInfo (internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc, TestInfo *test_info)
internal::ParameterizedTestSuiteRegistry & parameterized_test_registry ()
std::set< std::string > * ignored_parameterized_test_suites ()
internal::TypeParameterizedTestSuiteRegistry & type_parameterized_test_registry ()
void set_current_test_suite (TestSuite *a_current_test_suite)
void set_current_test_info (TestInfo *a_current_test_info)
void RegisterParameterizedTests ()
bool RunAllTests ()
void ClearNonAdHocTestResult ()
void ClearAdHocTestResult ()
void RecordProperty (const TestProperty &test_property)
int FilterTests (ReactionToSharding shard_tests)
void ListTestsMatchingFilter ()
const TestSuite * current_test_suite () const
TestInfo * current_test_info ()
const TestInfo * current_test_info () const
std::vector< Environment * > & environments ()
std::vector< TraceInfo > & gtest_trace_stack ()
const std::vector< TraceInfo > & gtest_trace_stack () const
void ConfigureXmlOutput ()
void PostFlagParsingInit ()
int random_seed () const
internal::Random * random ()
void ShuffleTests ()
void UnshuffleTests ()
bool catch_exceptions () const
Private Member Functions
void set_catch_exceptions (bool value)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl)
Private Attributes
UnitTest *const parent_
internal::FilePath original_working_dir_
DefaultGlobalTestPartResultReporter default_global_test_part_result_reporter_
DefaultPerThreadTestPartResultReporter default_per_thread_test_part_result_reporter_
TestPartResultReporterInterface * global_test_part_result_repoter_
internal::Mutex global_test_part_result_reporter_mutex_
internal::ThreadLocal< TestPartResultReporterInterface * > per_thread_test_part_result_reporter_
std::vector< Environment * > environments_
std::vector< TestSuite * > test_suites_
std::vector< int > test_suite_indices_
internal::ParameterizedTestSuiteRegistry parameterized_test_registry_
internal::TypeParameterizedTestSuiteRegistry type_parameterized_test_registry_
std::set< std::string > ignored_parameterized_test_suites_
bool parameterized_tests_registered_
int last_death_test_suite_
TestSuite * current_test_suite_
TestInfo * current_test_info_
TestResult ad_hoc_test_result_
TestEventListeners listeners_
OsStackTraceGetterInterface * os_stack_trace_getter_
bool post_flag_parse_init_performed_
int random_seed_
internal::Random random_
TimeInMillis start_timestamp_
TimeInMillis elapsed_time_
internal::ThreadLocal< std::vector< TraceInfo > > gtest_trace_stack_
bool catch_exceptions_
Friends
class ::testing::UnitTest
Detailed Description
Definition at line 495 of file gtest-internal-inl.h.
Member Enumeration Documentation
ReactionToSharding
enum testing::internal::UnitTestImpl::ReactionToSharding
Enumerator
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
Definition at line 740 of file gtest-internal-inl.h.
{
    HONOR_SHARDING_PROTOCOL,
    IGNORE_SHARDING_PROTOCOL
  };
Constructor & Destructor Documentation
UnitTestImpl()
testing::internal::UnitTestImpl::UnitTestImpl (UnitTest * parent) explicit
~UnitTestImpl()
virtual testing::internal::UnitTestImpl::~UnitTestImpl () virtual
Member Function Documentation
ad_hoc_test_result()
const TestResult * testing::internal::UnitTestImpl::ad_hoc_test_result () const inline
Definition at line 602 of file gtest-internal-inl.h.
{ return &ad_hoc_test_result_; }
AddTestInfo()
void testing::internal::UnitTestImpl::AddTestInfo (internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 658 of file gtest-internal-inl.h.
{
#if GTEST_HAS_DEATH_TEST
    // In order to support thread-safe death tests, we need to
    // remember the original working directory when the test program
    // was first invoked.  We cannot do this in RUN_ALL_TESTS(), as
    // the user may have changed the current directory before calling
    // RUN_ALL_TESTS().  Therefore we capture the current directory in
    // AddTestInfo(), which is called to register a TEST or TEST_F
    // before main() is reached.
    if (original_working_dir_.IsEmpty()) {
      original_working_dir_.Set(FilePath::GetCurrentDir());
      GTEST_CHECK_(!original_working_dir_.IsEmpty())
          << "Failed to get the current working directory.";
    }
#endif  // GTEST_HAS_DEATH_TEST
    GetTestSuite(test_info->test_suite_name(), test_info->type_param(),
                 set_up_tc, tear_down_tc)
        ->AddTestInfo(test_info);
  }
References GTEST_CHECK_, testing::TestInfo::test_suite_name(), and testing::TestInfo::type_param().
catch_exceptions()
bool testing::internal::UnitTestImpl::catch_exceptions () const inline
Definition at line 826 of file gtest-internal-inl.h.
{ return catch_exceptions_; }
ClearAdHocTestResult()
void testing::internal::UnitTestImpl::ClearAdHocTestResult () inline
Definition at line 730 of file gtest-internal-inl.h.
{
    ad_hoc_test_result_.Clear();
  }
ClearNonAdHocTestResult()
void testing::internal::UnitTestImpl::ClearNonAdHocTestResult () inline
Definition at line 725 of file gtest-internal-inl.h.
{
    ForEach(test_suites_, TestSuite::ClearTestSuiteResult);
  }
References testing::internal::ForEach().
ConfigureXmlOutput()
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
current_test_info() [1/2]
TestInfo * testing::internal::UnitTestImpl::current_test_info () inline
Definition at line 757 of file gtest-internal-inl.h.
{ return current_test_info_; }
current_test_info() [2/2]
const TestInfo * testing::internal::UnitTestImpl::current_test_info () const inline
Definition at line 758 of file gtest-internal-inl.h.
{ return current_test_info_; }
current_test_result()
TestResult * testing::internal::UnitTestImpl::current_test_result ()
current_test_suite()
const TestSuite * testing::internal::UnitTestImpl::current_test_suite () const inline
Definition at line 756 of file gtest-internal-inl.h.
{ return current_test_suite_; }
CurrentOsStackTraceExceptTop()
std::string testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop (int skip_count)
disabled_test_count()
int testing::internal::UnitTestImpl::disabled_test_count () const
elapsed_time()
TimeInMillis testing::internal::UnitTestImpl::elapsed_time () const inline
Definition at line 563 of file gtest-internal-inl.h.
{ return elapsed_time_; }
environments()
std::vector< Environment * > & testing::internal::UnitTestImpl::environments () inline
Definition at line 762 of file gtest-internal-inl.h.
{ return environments_; }
Failed()
bool testing::internal::UnitTestImpl::Failed () const inline
Definition at line 571 of file gtest-internal-inl.h.
                      {
    return failed_test_suite_count() > 0 || ad_hoc_test_result()->Failed();
  }
failed_test_count()
int testing::internal::UnitTestImpl::failed_test_count () const
failed_test_suite_count()
int testing::internal::UnitTestImpl::failed_test_suite_count () const
FilterTests()
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
GetGlobalTestPartResultReporter()
TestPartResultReporterInterface * testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter ()
GetMutableSuiteCase()
TestSuite * testing::internal::UnitTestImpl::GetMutableSuiteCase (int i) inline
Definition at line 589 of file gtest-internal-inl.h.
{
    const int index = GetElementOr(test_suite_indices_, i, -1);
    return index < 0 ? nullptr : test_suites_[static_cast<size_t>(index)];
  }
References testing::internal::GetElementOr().
GetTestCase() [1/2]
TestCase * testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc) inline
Definition at line 644 of file gtest-internal-inl.h.
{
    return GetTestSuite(test_case_name, type_param, set_up_tc, tear_down_tc);
  }
GetTestCase() [2/2]
const TestCase * testing::internal::UnitTestImpl::GetTestCase (int i) const inline
Definition at line 584 of file gtest-internal-inl.h.
{ return GetTestSuite(i); }
GetTestPartResultReporterForCurrentThread()
TestPartResultReporterInterface * testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread ()
GetTestSuite() [1/2]
TestSuite * testing::internal::UnitTestImpl::GetTestSuite (const char * test_suite_name, const char * type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
GetTestSuite() [2/2]
const TestSuite * testing::internal::UnitTestImpl::GetTestSuite (int i) const inline
Definition at line 577 of file gtest-internal-inl.h.
{
    const int index = GetElementOr(test_suite_indices_, i, -1);
    return index < 0 ? nullptr : test_suites_[static_cast<size_t>(i)];
  }
References testing::internal::GetElementOr().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::internal::UnitTestImpl::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl) private
gtest_trace_stack() [1/2]
std::vector< TraceInfo > & testing::internal::UnitTestImpl::gtest_trace_stack () inline
Definition at line 765 of file gtest-internal-inl.h.
{
    return *(gtest_trace_stack_.pointer());
  }
gtest_trace_stack() [2/2]
const std::vector< TraceInfo > & testing::internal::UnitTestImpl::gtest_trace_stack () const inline
Definition at line 768 of file gtest-internal-inl.h.
{
    return gtest_trace_stack_.get();
  }
ignored_parameterized_test_suites()
std::set< std::string > * testing::internal::UnitTestImpl::ignored_parameterized_test_suites () inline
Definition at line 687 of file gtest-internal-inl.h.
{
    return &ignored_parameterized_test_suites_;
  }
listeners()
TestEventListeners * testing::internal::UnitTestImpl::listeners () inline
Definition at line 595 of file gtest-internal-inl.h.
{ return &listeners_; }
ListTestsMatchingFilter()
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
os_stack_trace_getter()
OsStackTraceGetterInterface * testing::internal::UnitTestImpl::os_stack_trace_getter ()
parameterized_test_registry()
internal::ParameterizedTestSuiteRegistry & testing::internal::UnitTestImpl::parameterized_test_registry () inline
Definition at line 683 of file gtest-internal-inl.h.
{
    return parameterized_test_registry_;
  }
Passed()
bool testing::internal::UnitTestImpl::Passed () const inline
Definition at line 567 of file gtest-internal-inl.h.
{ return !Failed(); }
PostFlagParsingInit()
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
random()
internal::Random * testing::internal::UnitTestImpl::random () inline
Definition at line 815 of file gtest-internal-inl.h.
{ return &random_; }
random_seed()
int testing::internal::UnitTestImpl::random_seed () const inline
Definition at line 812 of file gtest-internal-inl.h.
{ return random_seed_; }
RecordProperty()
void testing::internal::UnitTestImpl::RecordProperty (const TestProperty & test_property)
RegisterParameterizedTests()
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
reportable_disabled_test_count()
int testing::internal::UnitTestImpl::reportable_disabled_test_count () const
reportable_test_count()
int testing::internal::UnitTestImpl::reportable_test_count () const
RunAllTests()
bool testing::internal::UnitTestImpl::RunAllTests ()
set_catch_exceptions()
void testing::internal::UnitTestImpl::set_catch_exceptions (bool value) inline private
Definition at line 833 of file gtest-internal-inl.h.
{ catch_exceptions_ = value; }
set_current_test_info()
void testing::internal::UnitTestImpl::set_current_test_info (TestInfo * a_current_test_info) inline
Definition at line 706 of file gtest-internal-inl.h.
{
    current_test_info_ = a_current_test_info;
  }
set_current_test_suite()
void testing::internal::UnitTestImpl::set_current_test_suite (TestSuite * a_current_test_suite) inline
Definition at line 699 of file gtest-internal-inl.h.
{
    current_test_suite_ = a_current_test_suite;
  }
set_os_stack_trace_getter()
void testing::internal::UnitTestImpl::set_os_stack_trace_getter (OsStackTraceGetterInterface * getter)
SetGlobalTestPartResultReporter()
void testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter (TestPartResultReporterInterface * reporter)
SetTestPartResultReporterForCurrentThread()
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
ShuffleTests()
void testing::internal::UnitTestImpl::ShuffleTests ()
skipped_test_count()
int testing::internal::UnitTestImpl::skipped_test_count () const
start_timestamp()
TimeInMillis testing::internal::UnitTestImpl::start_timestamp () const inline
Definition at line 560 of file gtest-internal-inl.h.
{ return start_timestamp_; }
successful_test_count()
int testing::internal::UnitTestImpl::successful_test_count () const
successful_test_suite_count()
int testing::internal::UnitTestImpl::successful_test_suite_count () const
test_suite_to_run_count()
int testing::internal::UnitTestImpl::test_suite_to_run_count () const
test_to_run_count()
int testing::internal::UnitTestImpl::test_to_run_count () const
total_test_count()
int testing::internal::UnitTestImpl::total_test_count () const
total_test_suite_count()
int testing::internal::UnitTestImpl::total_test_suite_count () const
type_parameterized_test_registry()
internal::TypeParameterizedTestSuiteRegistry & testing::internal::UnitTestImpl::type_parameterized_test_registry () inline
Definition at line 694 of file gtest-internal-inl.h.
{
    return type_parameterized_test_registry_;
  }
UnshuffleTests()
void testing::internal::UnitTestImpl::UnshuffleTests ()
Friends And Related Function Documentation
::testing::UnitTest
friend class ::testing::UnitTest friend
Definition at line 829 of file gtest-internal-inl.h.
Member Data Documentation
ad_hoc_test_result_
TestResult testing::internal::UnitTestImpl::ad_hoc_test_result_ private
Definition at line 907 of file gtest-internal-inl.h.
catch_exceptions_
bool testing::internal::UnitTestImpl::catch_exceptions_ private
Definition at line 947 of file gtest-internal-inl.h.
current_test_info_
TestInfo* testing::internal::UnitTestImpl::current_test_info_ private
Definition at line 897 of file gtest-internal-inl.h.
current_test_suite_
TestSuite* testing::internal::UnitTestImpl::current_test_suite_ private
Definition at line 891 of file gtest-internal-inl.h.
default_global_test_part_result_reporter_
DefaultGlobalTestPartResultReporter testing::internal::UnitTestImpl::default_global_test_part_result_reporter_ private
Definition at line 843 of file gtest-internal-inl.h.
default_per_thread_test_part_result_reporter_
DefaultPerThreadTestPartResultReporter testing::internal::UnitTestImpl::default_per_thread_test_part_result_reporter_ private
Definition at line 845 of file gtest-internal-inl.h.
elapsed_time_
TimeInMillis testing::internal::UnitTestImpl::elapsed_time_ private
Definition at line 933 of file gtest-internal-inl.h.
environments_
std::vector<Environment*> testing::internal::UnitTestImpl::environments_ private
Definition at line 859 of file gtest-internal-inl.h.
global_test_part_result_reporter_mutex_
internal::Mutex testing::internal::UnitTestImpl::global_test_part_result_reporter_mutex_ private
Definition at line 851 of file gtest-internal-inl.h.
global_test_part_result_repoter_
TestPartResultReporterInterface* testing::internal::UnitTestImpl::global_test_part_result_repoter_ private
Definition at line 848 of file gtest-internal-inl.h.
gtest_trace_stack_
internal::ThreadLocal<std::vector<TraceInfo> > testing::internal::UnitTestImpl::gtest_trace_stack_ private
Definition at line 943 of file gtest-internal-inl.h.
ignored_parameterized_test_suites_
std::set<std::string> testing::internal::UnitTestImpl::ignored_parameterized_test_suites_ private
Definition at line 879 of file gtest-internal-inl.h.
last_death_test_suite_
int testing::internal::UnitTestImpl::last_death_test_suite_ private
Definition at line 885 of file gtest-internal-inl.h.
listeners_
TestEventListeners testing::internal::UnitTestImpl::listeners_ private
Definition at line 911 of file gtest-internal-inl.h.
original_working_dir_
internal::FilePath testing::internal::UnitTestImpl::original_working_dir_ private
Definition at line 840 of file gtest-internal-inl.h.
os_stack_trace_getter_
OsStackTraceGetterInterface* testing::internal::UnitTestImpl::os_stack_trace_getter_ private
Definition at line 917 of file gtest-internal-inl.h.
parameterized_test_registry_
internal::ParameterizedTestSuiteRegistry testing::internal::UnitTestImpl::parameterized_test_registry_ private
Definition at line 873 of file gtest-internal-inl.h.
parameterized_tests_registered_
bool testing::internal::UnitTestImpl::parameterized_tests_registered_ private
Definition at line 882 of file gtest-internal-inl.h.
parent_
UnitTest* const testing::internal::UnitTestImpl::parent_ private
Definition at line 836 of file gtest-internal-inl.h.
per_thread_test_part_result_reporter_
internal::ThreadLocal<TestPartResultReporterInterface*> testing::internal::UnitTestImpl::per_thread_test_part_result_reporter_ private
Definition at line 855 of file gtest-internal-inl.h.
post_flag_parse_init_performed_
bool testing::internal::UnitTestImpl::post_flag_parse_init_performed_ private
Definition at line 920 of file gtest-internal-inl.h.
random_
internal::Random testing::internal::UnitTestImpl::random_ private
Definition at line 926 of file gtest-internal-inl.h.
random_seed_
int testing::internal::UnitTestImpl::random_seed_ private
Definition at line 923 of file gtest-internal-inl.h.
start_timestamp_
TimeInMillis testing::internal::UnitTestImpl::start_timestamp_ private
Definition at line 930 of file gtest-internal-inl.h.
test_suite_indices_
std::vector<int> testing::internal::UnitTestImpl::test_suite_indices_ private
Definition at line 869 of file gtest-internal-inl.h.
test_suites_
std::vector<TestSuite*> testing::internal::UnitTestImpl::test_suites_ private
Definition at line 863 of file gtest-internal-inl.h.
type_parameterized_test_registry_
internal::TypeParameterizedTestSuiteRegistry testing::internal::UnitTestImpl::type_parameterized_test_registry_ private
Definition at line 875 of file gtest-internal-inl.h.
The documentation for this class was generated from the following file:
gtest-internal-inl.h