MUSI6106: testing::internal::TestResultAccessor Class Reference
testing::internal::TestResultAccessor Class Reference
#include <gtest-internal-inl.h>
Static Public Member Functions
static void RecordProperty (TestResult *test_result, const std::string &xml_element, const TestProperty &property)
static void ClearTestPartResults (TestResult *test_result)
static const std::vector< testing::TestPartResult > & test_part_results (const TestResult &test_result)
Detailed Description
Definition at line 1028 of file gtest-internal-inl.h.
Member Function Documentation
ClearTestPartResults()
static void testing::internal::TestResultAccessor::ClearTestPartResults (TestResult * test_result) inline static
Definition at line 1036 of file gtest-internal-inl.h.
{
    test_result->ClearTestPartResults();
  }
References testing::TestResult::ClearTestPartResults().
RecordProperty()
static void testing::internal::TestResultAccessor::RecordProperty (TestResult * test_result, const std::string & xml_element, const TestProperty & property) inline static
Definition at line 1030 of file gtest-internal-inl.h.
{
    test_result->RecordProperty(xml_element, property);
  }
References testing::TestResult::RecordProperty().
test_part_results()
static const std::vector< testing::TestPartResult > & testing::internal::TestResultAccessor::test_part_results (const TestResult & test_result) inline static
Definition at line 1040 of file gtest-internal-inl.h.
{
    return test_result.test_part_results();
  }
References testing::TestResult::test_part_results().
The documentation for this class was generated from the following file:
gtest-internal-inl.h